### ISSUE TITLE
Control header start page for article doctype

### ISSUE THREAD

**Issue by dohliam** [asciidoctor/asciidoctor-pdf#1403] opened 2019-11-23 22:30 UTC
It is not currently possible to configure the starting page position of running content for the article doctype.

As of #945 it is possible to specify the position of the running content (headers and footers) in the document using a theme file, e.g.:

```yml
running_content:
  start_at: toc
```

This is a great improvement. However, it only applies to the book doctype -- setting the `start_at` variable has no effect for article doctypes (unless they have a title page set).

This is because the value of `start_at` is explicitly only read from the theme file if [a title page is set](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor/pdf/converter.rb#L226). Otherwise, both header and footer are hardcoded to [start on the first page of the document](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor/pdf/converter.rb#L249).

Nevertheless, it would be ideal to be able to configure this for all article types, including articles without title pages. An example of a situation where this would be needed is regular articles where the running header contains the title and/or author name. Currently this results in roughly the following PDF output:

```
[HEADER] TITLE

[H1] TITLE

Article text
```

The duplicate title at the top of the page looks quite odd, and for this reason is usually omitted on the first page of articles. The exception of course as reported in #606 is for articles where organizational or other information is required to be printed on each page, including the title.

Since I had the opposite requirement (i.e., the appearance of the header on the first page of the article was not acceptable), I patched [Line 249 of converter.rb](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor/pdf/converter.rb#L249) to the following:

```rb
num_front_matter_pages = [@theme.running_content_start_at, body_start_page_number - 1]
```

This allows for the start page to be specified by setting `start_at` to any desired position in the theme file and works quite well for my use case (since I don't ever have the need to print a header on the first page of articles).

However, for this to be more generally useful, it would need to address a few other factors:

1. Only read from the theme file if the `start_at` variable has been specified
2. Default to current behaviour if the above variable is _not_ set
3. Allow for the footer position to be specified separately (e.g., when numbering in the footer is still needed even when there is no header)

I think it should be fairly straightforward to accommodate the first two of these using something like the following starting on Line 248:

```rb
      elsif @theme.page_numbering_start_at
        num_front_matter_pages = [@theme.running_content_start_at, body_start_page_number - 1]
      else
        num_front_matter_pages = [body_start_page_number - 1] * 2
      end
```

This would preserve the current default behaviour, but make it optionally configurable using a theme file, as is already possible for the book doctype. EDIT: I'm not sure how to separate the footer configuration though.

From reading through the other issues, it seems a possible stumbling block might be the unpredictable effect of starting page numbering on arbitrary pages, [EDIT] though from a few tests this seems to have been solved already. In any case, it would be great to have this additional flexibility of being able to control the appearance of the header and footer without having to re-patch the gem source on each update.

**Comment by mojavelinux** [comment] 2020-01-02 06:42
This is a duplicate of #1455. To start the running content after the first page, set the running_content_start_at to the value 2 (instead of the default 1). To start the page numbering after the first page, set the page_numbering_start_at to the value 2 (instead of the default 1).

**Closed** 2020-01-02 06:42 UTC
Labels: duplicate
