### ISSUE TITLE
Table extends beyond right margin to edge of paper

### ISSUE THREAD

**Issue by 1marc1** [asciidoctor/asciidoctor-pdf#1945] opened 2021-07-05 13:36 UTC
Thank you again to everyone working on making the Asciidoctor tool set so great. In addition to the table issue I reported earlier, I may have found another issue whereby the table extends beyond the configured margin right to the edge of the paper.

I have tested this with both Asciidoctor-PDF 1.5.3 and 1.6.0 and the result is the same.

Consider the following table (I have replaced an inline icon image for the word ICON):
```
[cols="2h,6,2",frame=all,grid=all]
|===
2+| Physical Installation  .2+| ICON 
| Check | Visual audit found...  
| Observation 2+| Device was installed...  
| Impact 2+| Installing devices above...  
| Recommendation 2+| Install device below...  
|===
```

This results in a table that respects the left margin, but not the right margin.

![image](https://user-images.githubusercontent.com/18713538/124479178-5948e500-dde9-11eb-900c-90890c07d2cc.png)

It would be great if someone could have a look into this.

Thank you.

Marc.

**Comment by mojavelinux** [comment] 2021-07-06 06:17
This is a duplicate of #1368. Please search the issue tracker before filing new issues to avoid duplicates.

**Closed by mojavelinux** 2021-07-06 06:17 UTC

**Comment by 1marc1** [comment] 2021-07-06 12:26
Apologies for the duplicate. My searches prior to posting did not find the issue you reference.
