### ISSUE TITLE
background color for captions

### ISSUE THREAD

**Issue by flowchartsman** [asciidoctor/asciidoctor-pdf#1995] opened 2022-02-04 19:45 UTC
I would love to be able to have listing titles that stand out by being inverted versions of the standard headings. Like the following:

![image](https://user-images.githubusercontent.com/926884/152593286-31e3e603-c175-431f-96b7-2337ef705f95.png)

If that's possible without using a role in the listing title, that would be grand! (fullwidth background color block a bonus)

**Comment by mojavelinux** [comment] 2022-04-25 08:59
Here's how you can add a background to captions for code blocks using a custom converter:

```rb
class MyPdfConverter < (Asciidoctor::Converter.for 'pdf')
  register_for 'pdf'

  def layout_caption subject, opts = {}
    if opts[:category] == :code && !scratch?
      force_top_margin = !at_page_top? if (force_top_margin = opts.delete :force_top_margin).nil?
      caption_height = (dry_run keep_together: true, single_page: :enforce do
        margin_box.instance_variable_set :@y, margin_box.absolute_top + 0.0001 if force_top_margin
        indent 3 do
          layout_caption subject, opts
        end
      end).single_page_height
      caption_height -= (@theme.code_caption_margin_inside || @theme.caption_margin_inside)
      float do
        bounding_box([0, cursor], width: bounds.width, height: caption_height) { fill_bounds '85210C' }
      end
      indent(3) { super }
    else
      super
    end
  end
end
```

You could do something similar for section titles by overriding `layout_general_heading` (or `arrange_section`).

**Comment by mojavelinux** [comment] 2022-04-25 09:16
Let's keep this issue focused on a single feature. I've opted to focus on background colors for caption since we know how to do it and I see a path to supporting it.

**Comment by mojavelinux** [comment] 2022-04-25 09:18
The request to set a background for headings is actually a duplicate of #434 anyway.

**Closed** 2022-04-26 00:28 UTC
Labels: enhancement
