### ISSUE TITLE
Using the same color syntax to convert in HTML and PDF and manage colors in YAML file

### ISSUE THREAD

**Issue by JBR69** [asciidoctor/asciidoctor-pdf#476] opened 2016-07-12 10:20 UTC
Hi,

I'm starting to convert all my documents word in asciidoc (about fifty) and my goal is to convert these doc in html and in PDF.
So I use asciidoctor and ascidoctor-pdf.

My problem is with the color text.
In the doc I write, for example, `[myColorName]#my text#` and in the CSS file, I declare a class `.myColorName: #hexa_color_code`
-> It's OK when I convert in HTML

I would to do the same in PDF conversion; but it doesn't work.
Then I have to write this code in my asciiDoc `+++<span style="color: #hexa_color_code">my text</span>+++`. 
It works in PDF and in HTML but the syntax is more complex and the color code is written in hard in the document and I don't want it

So I modified the `asciidoctor-pdf` code to add these lines in the file `transform.rb`  

**line 208** (block `when :span` in `build_fragment(fragment, tag_name, attrs = {})` before the line `# span logic with normal style parsing`

> ```
>   # *********************************************************************************************
>   if (!attrs[:class].nil? and attrs[:class] != '')
>       pvalue = attrs[:class]
>       if pvalue.start_with? '#'
>           # hexa color code
>           pvalue = pvalue[1..-1] 
>       else
>           # color name -> get color code in the theme file (yaml)             
>           # (I deliberately add suffix _color)
>           pvalue = @theme[%(#{pvalue}_color)]
>           if pvalue.nil? or pvalue == ''
>               pvalue = '000000'
>           end
>       end
>       fragment[:color] = pvalue           
>   end
>   # *********************************************************************************************
> ```

In the same file, I transform variable `theme` to `@theme`
And I add in YAML file, the corresponding color `myColorName_color: hexa_color_code`

Now I can manage color in the same way as HTML (via CSS file ) in PDF (via YAML file).
But as I am a beginner in Ruby and asciidoctor, is the right way to do what I want ?
And do you intend to integrate this type of mechanism in `asciidoctor-pdf` ?

Thank you,
Best regards,
Jerome

PS : sorry for poor english ;-)

**Comment by mojavelinux** [comment] 2016-08-14 09:41
This is a duplicate of #368 (though with a lot more detail). We should take it a step further than what you are proposing and link font settings to a role, which can then be mapped to a phrase.

**Comment by JBR69** [comment] 2016-11-09 14:37
In #652, I use a better solution that matches issue #368

**Comment by mojavelinux** [comment] 2019-07-30 10:08
It will be possible to set font color roles in your theme starting in 1.5.0.beta.2. See #368 (and the theming guide) for details.

**Closed by mojavelinux** 2019-07-30 10:08 UTC
Labels: enhancement
