### ISSUE TITLE
asciidoctor: WARNING: conversion missing in backend pdf for stem

### ISSUE THREAD

**Issue by siddjain** [asciidoctor/asciidoctor-pdf#1176] opened 2019-07-26 23:30 UTC
Hello, I am new to asciidoc. I wrote an asciidoc in which I use stem as explained in https://asciidoctor.org/docs/user-manual/#activating-stem-support. But when I try to produce a pdf I get an error:

```
$ asciidoctor-pdf chap01.adoc
asciidoctor: WARNING: conversion missing in backend pdf for stem
```

and the generated pdf does not render STEM content. I have installed `asciimath` gem

```
$ gem install asciimath
Fetching asciimath-1.0.8.gem
Successfully installed asciimath-1.0.8
Parsing documentation for asciimath-1.0.8
Installing ri documentation for asciimath-1.0.8
Done installing documentation for asciimath after 0 seconds
1 gem installed
```

I also tried some other variations of generating pdf but none of them worked.
```
$ asciidoctor-pdf -a stem -r asciidoctor-pdf  -b pdf chap01.adoc
```

How can I fix this?

**Comment by mojavelinux** [comment] 2019-07-26 23:40
To get STEM support for Asciidoctor PDF, you need to use [asciidoctor-mathematical](https://github.com/asciidoctor/asciidoctor-mathematical). This is covered in the README here: https://github.com/asciidoctor/asciidoctor-pdf#stem-support

This is esseentially a duplicate of #1113.

(There's also an experimental extension for using mathoid in the extension lab. Please see https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/105 for the future plans).

**Closed by mojavelinux** 2019-07-26 23:40 UTC

**Comment by siddjain** [comment] 2019-07-26 23:46
Thanks @mojavelinux I tried following the steps to install asciidoctor-mathematical. I was able to brew install glib gdk-pixbuf cairo pango cmake

and followed it by installating the font dependencies. But when I ran`gem install asciidoctor-mathematical` I am getting errors. see https://gist.github.com/siddjain/1977083addcff41e9a474dcac42ea02c

How can I fix that? 

The doc says 

> If you experience any compilation errors (caused by Mathematical) try running: brew link gettext --force (you can unlink the libraries later if you want).

I am not sure what above does. How can I "unlink" later on? SHould I even try this?

**Comment by mojavelinux** [comment] 2019-07-27 00:33
As I mentioned in #1113, this is not the correct place to discuss asciidoctor-mathematical (because the code for it is not here). Please look for or open an issue in the asciidoctor-mathematical project to get help.

(FYI, the mathoid extension is likely going to be a lot simpler since it doesn't require native libraries. However, that project still hasn't materialized, as we're discussing in https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/105).

**Comment by siddjain** [comment] 2019-07-27 21:05
OK, so the TL;DR I am getting is that typesetting math is not supported in asciidoc.

Could someone give me instructions on how to use mathoid? We cloned the extensions repo. first we got this error while trying to run the sample:
https://gist.github.com/siddjain/fe38bcb39645ee0d37364f953b9a4a8a

Then after some searching it became apparent that we have to npm install mathoid. we tried that and got this error:
https://gist.github.com/siddjain/9502cd45ca56f7f19e03ad5897717527


________________________________

**Comment by mojavelinux** [comment] 2019-07-28 02:24
> OK, so the TL;DR I am getting is that typesetting math is not supported in asciidoc.

That is not the TL;DR. The TL;DR is that stem support is provided by different integration libraries for different backends. For PDF, the integration library is currently asciidoctor-mathematical. Due to the requirements of asciidoctor-mathematical, it can be hard to install on some machines. But it works perfectly well in the [Asciidoctor docker image](https://github.com/asciidoctor/docker-asciidoctor). If you need help, spreading FUD is not how you get it. It's asking honest questions in the right channel.

If you have questions about the mathoid integration, please ask on this issue: https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/71
