### ISSUE TITLE
asciidoctor-pdf -v throws exception (undefined method `checksum')

### ISSUE THREAD

**Issue by simtec66** [asciidoctor/asciidoctor-pdf#1466] opened 2020-01-06 09:25 UTC
Hi
I installed ruby 2.7.0 via chocolatey. I tried to install asciidoctor-pdf via _gem install_ but tried also _bundle install_. However in both cases I get the following error:

```
PS Z:\> asciidoctor-pdf -v
Traceback (most recent call last):
        10: from C:/tools/ruby27/bin/asciidoctor-pdf:23:in `<main>'
         9: from C:/tools/ruby27/bin/asciidoctor-pdf:23:in `load'
         8: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/asciidoctor-pdf-1.5.0.beta.8/bin/asciidoctor-pdf:5:in `<top (required)>'
         7: from C:/tools/ruby27/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         6: from C:/tools/ruby27/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         5: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf.rb:5:in `<top (required)>'
         4: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf.rb:5:in `require_relative'
         3: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf/converter.rb:4:in `<top (required)>'
         2: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf/converter.rb:4:in `require_relative'
         1: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf/ext/ttfunk.rb:3:in `<top (required)>'
C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf/ext/ttfunk.rb:4:in `<class:Base>': undefined method `checksum' for class `TTFunk::Subset::Base' (NameError)
```
The starnge thing is that it runs perfectly well on an older computer. Is Ruby 2.7 compatible with _asciidoctor-pdf_?

Thanks for any help

**Comment by mojavelinux** [comment] 2020-01-06 10:21
This is a duplicate of #1461 and has already been fixed in master.

**Closed by mojavelinux** 2020-01-06 10:21 UTC

**Comment by simtec66** [comment] 2020-01-06 10:25
Thanks a lot!
