### ISSUE TITLE
Table overflows right edge of page when converting to PDF

### ISSUE THREAD

**Issue by WatsonMC** [asciidoctor/asciidoctor-pdf#1968] opened 2021-09-15 05:32 UTC
Hello, 

I've found a problem when creating some especially finicky tables.

I have not pinpointed the exact causal conditions, and which are superfluous, but when creating a table where:
- The first row **spans all columns**
- The second row first column **spans two rows**
- The second row last column **spans two rows**
- The second row second column cell spans **two columns**
- All rows from three onward have the second column cell **spanning two columns**

The table will flow over the right edge of the page when converting to PDF. Highlighted in 'red cross' on image.
![image](https://user-images.githubusercontent.com/37425298/133375583-b53c59b1-f204-4f13-99f2-e4f56e0372d8.png)

The issue is not present in the Visual Studio Code preview view. In that view, the table appears formatted correctly.

I can prevent the issue by ensuring at least one of the rows from three onward does not have a two-column spanning cell in column 2. This is marked with the green tick in image. 

Asciidoc text below:
-------------
This table will format over the edge of the page when turned to PDF.

.Failure table
[cols="2,1,1,2"]
|===
 4+h| Product Label Requirements
.2+h| Parameter
 2+h| Value 
.2+h| Comment

h| Type 1
h| Type 2

//table guts
| Column 1, row 1   2+|         |       
| Column 1, row 2   2+|         | All rows have some merging, vertical or horizontal       
| Column 1, row 3   2+|         |       
| Column 1, row 4   2+|         |       
| Column 1, row 5   2+|         |       
|===

This Table will not format over the edge of the page when turned to PDF.

.Success table
[cols="2,1,1,2"]
|===
 4+h| Product Label Requirements
.2+h| Parameter
 2+h| Value / Quantity
.2+h| Comment

h| LPA Type 1
h| LPA Type 2

//table guts
| Column 1, row 1   2+|                         |       
| Column 1, row 2     |Populated  |Columns      | row with all 4 columns and no vertical or horz merging      
| Column 1, row 3   2+|                         |       
| Column 1, row 4   2+|                         |       
| Column 1, row 5   2+|                         |       
|===
[Test1.adoc.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/7166974/Test1.adoc.txt)

**Comment by mojavelinux** [comment] 2021-09-15 07:55
This is a known issue and a duplicate of #1368.

**Closed by mojavelinux** 2021-09-15 07:55 UTC
