### ISSUE TITLE
Index Sorting: Case Insensitive

### ISSUE THREAD

**Issue by tajmone** [asciidoctor/asciidoctor-pdf#1406] opened 2019-11-24 09:21 UTC
(problem encountered using Asciidoctor PDF, see #928).

In the Index of a PDF document converted via Asciidoctor PDF, the entries for each letter are sorted Asciibetically, instead of alhpabetically.

Entries in uppercase are listed before entries in lowercase, which leads to differently cased same-entries to be separated by other entries which would normally come after them:

```
AAA
BBB
CCC
aaa
```

... where one would expect "aaa" to directly follow "AAA".

This makes looking up entries in the Index troublesome, as the reader is forced to jump up and down the entries list to check differently cased entries are available for a given term — needless to say, it could lead to missing out many entries that are actually indexed.

**Comment by mojavelinux** [comment] 2019-11-25 06:05
Oops, looks like we both filed the same issue. Duplicate of #1405.

**Closed by mojavelinux** 2019-11-25 06:05 UTC
