### ISSUE TITLE
Wrong Warning message "image not found" in PDF generation

### ISSUE THREAD

**Issue by Olivier-Heintz** [asciidoctor/asciidoctor-pdf#1783] opened 2020-10-05 18:31 UTC
Document is generated correctly for html and pdf, all planned images are present in the two format.
But the pdf generation print some warning : 
```
AVERTISSEMENT: image to embed not found or not readable: /home/devel/ofbiz-svn/ofbiz-framework/plugins/birt/src/docs/asciidoc/_include/Report-Master.png
oct. 05, 2020 12:06:04 PM uri:classloader:/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb convert_inline_image
```
It's strange because the correct path is home/devel/ofbiz-svn/ofbiz-framework/plugins/birt/src/docs/asciidoc/images/birt/Report-Master.png
in the main adoc file which is in ..../birt/src/docs/asciidoc directory, there is a imagesDir affectation
```

= Birt OFBiz® plugin
The Apache OFBiz Project
ifdef::backend-pdf[]
:title-logo-image: image::../OFBiz-Logo.svg[Apache OFBiz Logo, pdfwidth=4.25in, align=center]
:source-highlighter: rouge
endif::[]
:imagesdir: ./images/birt

```
images are used in included files located in ..../birt/src/docs/asciidoc/_include directory

Asciidoc generation is run with gradle (6.5.1) with
- id 'org.asciidoctor.convert' version '2.4.0'
- asciidoctor 'org.asciidoctor:asciidoctorj-pdf:1.5.3'
- asciidoctor 'org.jruby:jruby-complete:9.2.11.1'

Hoping it's clear, and all necessary details are present
If not ask me.

If it's a problem already declare, thank you to give me link to declaration / solution

**Comment by mojavelinux** [comment] 2020-10-05 23:41
Issue transferred to the asciidoctor-pdf repository as this pertains to the Asciidoctor PDF converter.

**Comment by mojavelinux** [comment] 2020-10-05 23:52
It must be that the build configuration is setting the imagesdir attribute (or perhaps base_dir option) in a way that you don't expect. When I try it with the asciidoctor-pdf command directly, it works fine. (https://github.com/apache/ofbiz-plugins/tree/trunk/birt/src/docs/asciidoc)

Can you point me to where the build script is for this project? Perhaps I can give you a hint. What I would advise is to review that build script.

**Comment by Olivier-Heintz** [comment] 2020-10-06 13:34
Thank you for your answer,

There was an error in birt.adoc header  in my first message, the correct one is 
```
= Birt OFBiz® plugin
The Apache OFBiz Project
ifdef::backend-pdf[]
:title-logo-image: image::images/OFBiz-Logo.svg[Apache OFBiz Logo, pdfwidth=4.25in, align=center]
:source-highlighter: rouge
endif::[]

:imagesdir: ./images/birt

```

the build script : 
```
tasks.withType(AsciidoctorTask) { task ->
    backends 'html5', 'pdf'
    attributes \
        'doctype': 'book',
        'revnumber': 'Trunk',
        'experimental': '',
        'allow-uri-read': true,
        'icons': 'font',
        'sectnums': '',
        'chapter-label': '',
        'toc': 'left@',
        'toclevels': '3'
}

task deleteAllPluginsDocumentation {
    doFirst { delete "${buildDir}/asciidoc/plugins" }
}

task generateAllPluginsDocumentation(group: docsGroup,
        description: 'Generate all plugins documentation.') {

    dependsOn deleteAllPluginsDocumentation
    file("${pluginsDir}").eachDir { plugin ->
        activeComponents().each { component ->
            if (component.name == plugin.name) {
                if (subprojectExists(":plugins:${plugin.name}")) {
                    def pluginAsciidoc = task "${component.name}-Documentation" (type: AsciidoctorTask) {
                        def asciidocFolder = new File("${component}/src/docs/asciidoc")
                        doFirst {
                            if (asciidocFolder.exists()) {
                               // For :title-logo-image:
                                copy {
                                    from "${rootDir}/docs/asciidoc/images/OFBiz-Logo.svg"
                                    into "${component}/src/docs/asciidoc/images"
                                }
                            }
                        }
                        if (asciidocFolder.exists()) {
                            sourceDir file("${component}/src/docs/asciidoc")
                            outputDir file("${buildDir}/asciidoc/plugins/${component.name}")
                            doLast { println "Documentation generated for plugin ${component.name}" }
                        }
                    mustRunAfter deleteAllPluginsDocumentation
                    doLast { delete "${component}/src/docs/asciidoc/images/OFBiz-Logo.svg" }
                    }
                    dependsOn pluginAsciidoc
                }
            }
        }
    }
}
```
it's possible to see the generation log : 
https://ci.apache.org/builders/ofbizTrunkFrameworkPlugins/builds/1836/steps/generateAllPluginsDocumentation/logs/stdio

it's possible to view the result : 
https://ci.apache.org/projects/ofbiz/site/trunk/pluginsdoc/birt/pdf/birt.pdf

To add some details about plugins documentation, 
1. currently documentation is published in two format: 
    - first one, included in the user-manual, which contain all component documentation (https://ci.apache.org/projects/ofbiz/site/trunk/ofbizdoc/pdf/user-manual.pdf  chapter Apache OFBiz plugins)
    - second one, with one document per plugin
2. to be able to publish user-manual in html, each plugin put its image in its images/${component.name} directory, which is copied (by gradle) in the general images directory just before generation
3. currently we are just finishing migration to asciidoc format  and are working to put more content on documentation. Install and use Antora will be the next step

**Comment by mojavelinux** [comment] 2021-02-24 09:32
There's not enough information here to reproduce this problem (I can't even find the build.gradle script that has the Asciidoctor task configuration in it). If this is a still a problem for you, please reopen and provide a runnable example.

My guess is that in addition to the main file, the plugin is also converting individual include files, which is where the image path gets computed incorrectly. That's why you get both the correct output and the warning. But I can only guess without a runnable example that I can investigate.

**Comment by mojavelinux** [comment] 2021-02-24 09:33
You also may want to file the issue with the Gradle plugin (https://github.com/asciidoctor/asciidoctor-gradle-plugin) since this really doesn't have anything to do with the PDF converter itself.

**Closed by mojavelinux** 2021-02-24 09:32 UTC
