### ISSUE TITLE
chapter-signifier doesn't work with toc

### ISSUE THREAD

**Issue by edusantana** [asciidoctor/asciidoctor-pdf#1305] opened 2019-10-05 15:40 UTC
If I have a file `without-toc.adoc`:

```asciidoc
= Guia do Desenvolvimento de Aplicações WEB
Eduardo de Santana Medeiros Alexandre
:doctype: book
:sectnums:

:chapter-signifier: Capítulo

== First

Some text
```

And run `asciidoctor-pdf without-toc.adoc` it will produce [without-toc.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/3693421/without-toc.pdf) (chapter-signifier works)

But if I have `with-toc.adoc`:

```asciidoc
= Guia do Desenvolvimento de Aplicações WEB
Eduardo de Santana Medeiros Alexandre
:doctype: book
:sectnums:
:toc:
:chapter-signifier: Capítulo

== First

Some text

```

It produces [with-toc.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/3693424/with-toc.pdf), but doesn't have "Capítulo".

```bash
$ asciidoctor-pdf --version
Asciidoctor PDF 1.5.0.beta.5 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by edusantana** [comment] 2019-10-05 20:49
It looks like the code from the master gets it right. I have made a automated test, but it pass.

**Comment by mojavelinux** [comment] 2019-10-06 08:30
This is by design. The TOC does not use the signifier, as is customary based on my understanding. We could consider adding a key to the theme to specify that the toc should use formal section titles (which include the signifier). Perhaps something like:

```
toc:
  # options include: default, document, title
  refstyle: document
```

Which says use the same refstyle used in the document, building on the refstyle concept that controls this output elsewhere.

Related to https://github.com/asciidoctor/asciidoctor-pdf/issues/1044#issuecomment-508984635

**Comment by edusantana** [comment] 2019-10-06 18:23
@mojavelinux i'm **not** saing _chapter-signifier doesn't work **within** the toc_. I'm saying that it is not working **when** I include a toc. And this behavior is on the version `1.5.0.beta.5`. 

Latter on, when I was trying to reproduce the problem on a automated test, I discovered that the code on the `master branch` has a different behavior, and it's the correct one. It allows the use of `chapter-signifier` even when we include a toc.

**Comment by mojavelinux** [comment] 2019-10-06 20:11
Ahhhhhhhh. Thanks for clarifying. Good to know that was fixed. I'll make a note of it in the release notes. :+1:

**Comment by mojavelinux** [comment] 2019-10-06 20:17
As far as I can tell, this works fine with beta.5. Are you sure you didn't have a blank line before the `chapter-signifier` attribute entry? It must be defined in the document header.

**Comment by mojavelinux** [comment] 2019-10-06 20:20
I've added a test for this combination just in case.

**Comment by edusantana** [comment] 2019-10-07 11:00
Yes... that's the problem, the blank line! It would be nice to have a **warning** if we set a header only attribute outside the document header.

**Comment by mojavelinux** [comment] 2019-10-07 18:51
Glad to hear that resolved it.

> It would be nice to have a warning if we set a header only attribute outside the document header.

That's now how AsciiDoc works. The attribute declaration is valid either way. It just doesn't carry the same meaning. There are two things that would help, though. First, is the proposal to allow blank lines between attribute entries in the header (since this is clearly an instinctual thing to do). See https://github.com/asciidoctor/asciidoctor/issues/3267. The other is a validator, which could look for these types of intention errors and warn you about them. See https://github.com/asciidoctor/asciidoctor/issues/2892.

Since neither have to do directly with Asciidoctor PDF, I'll close this issue so we can continue the discussion in one of those two places.

**Closed by mojavelinux** 2019-10-07 18:51 UTC
