### ISSUE TITLE
Allow minitoc (toc per chapter)

### ISSUE THREAD

**Issue by edusantana** [asciidoctor/asciidoctor-pdf#1298] opened 2019-09-28 12:31 UTC
It would be nice be able to genarate a mini-toc for each chapter. It's very useful when we are going to share separated chapters of a book on a Learning course.

I have used it in the past with asciidoc and dblatex. Here's an example: [analise-e-projeto-sistemas-livro-v0.7.0.pdf](https://github.com/ufpb-computacao/analise-e-projeto-sistemas-livro/releases/download/v0.7.0/analise-e-projeto-sistemas-livro-v0.7.0.pdf) 

I had to customize the template of the generation: [latex/computacao.sty](https://github.com/ufpb-computacao/producao-computacao-ead-ufpb/blob/91a58697429cde0a27605b85ff73e4dbe222ef6c/dblatex-computacao-ufpb/computacao/latex/computacao.sty#L32-L33)

I was inspired by the [debian-handbook](https://debian-handbook.info/download/wheezy/debian-handbook.pdf) minitoc. Here's a seach of [minitoc on its repository](https://github.com/ieugen/debian-handbook/search?q=minitoc&unscoped_q=minitoc)

- [minitoc package](http://www.ctan.org/pkg/minitoc)
- [old issue about it](https://github.com/ufpb-computacao/producao-computacao-ead-ufpb/issues/27)

**Comment by mojavelinux** [comment] 2019-09-29 06:36
This is extremely challenging with this PDF generator (Prawn). In fact, we still haven't even managed yet to be able to move the full toc around. The problem is that the toc needs to know the pages and reference object of the target when it is written, but those don't come until after the toc. So it's necessary to reserve space for the toc, then come back and write the toc once you have that information. (And it gets even more complex if the toc needs to be on its own page). So while I agree it would be nice, I don't see myself having time to work on this. But if someone wants to figure it out, I encourage that person to do so.

**Comment by vlgarant** [comment] 2020-10-22 20:43
was there any progress with it or is it still complicated in PDFs?

**Comment by mojavelinux** [comment] 2020-10-22 20:45
We can now move the toc around, but this remains fairly complicated (because creating a TOC is not easy). You are free to extend the converter and try to add it yourself. I probably won't work on adding this to the converter otherwise. It's not something I really want to spend time on.

**Comment by vlgarant** [comment] 2020-10-22 20:46
fair enough, i'll try looking into it (no promises though)

**Comment by mojavelinux** [comment] 2022-04-29 10:44
Here's an absurdly simple implementation of this using an extended converter:

```rb
class MyPdfConverter < (Asciidoctor::Converter.for 'pdf')
  register_for 'pdf'

  def convert_section sect, opts = {}
    result = super
    if (toc_extent = sect.attr 'pdf-toc-extent')
      float do
        inscribe_toc sect, 3, toc_extent.from.page, toc_extent.from.cursor, 1
      end
    end
    result
  end

  def inscribe_chapter_title sect, title, opts
    super
    theme_font :base do
      old_toc_extent = @toc_extent
      sect.set_attr 'pdf-toc-extent', (allocate_toc sect, 3, cursor, false) 
      @toc_extent = old_toc_extent
    end
  end
end
```

If we could figure out how to express from AsciiDoc when to enable this functionality, we might be able to put this into this converter. I'm looking for proposals.

**Comment by mojavelinux** [comment] 2022-04-29 10:55
We could do something like `chapter-toc` and `chapter-toclevels`:

```
= Document Title
:chapter-toc:
:chapter-toclevels: 2

...
```

Here's how that would look:

```rb
class MyPdfConverter < (Asciidoctor::Converter.for 'pdf')
  register_for 'pdf'

  def convert_section sect, opts = {}
    result = super
    if (toc_extent = sect.attr 'pdf-toc-extent')
      levels = (sect.document.attr 'chapter-toclevels', 1).to_i + 1
      page_numbering_offset = @index.start_page_number - 1
      float do
        inscribe_toc sect, levels, toc_extent.from.page, toc_extent.from.cursor, page_numbering_offset
      end
    end
    result
  end

  def inscribe_chapter_title sect, title, opts
    super
    if ((doc = sect.document).attr? 'chapter-toc') && (levels = (doc.attr 'chapter-toclevels', 1).to_i + 1) > 1
      old_toc_extent = @toc_extent
      theme_font :base do
        sect.set_attr 'pdf-toc-extent', (allocate_toc sect, levels, cursor, false)
      end
      @toc_extent = old_toc_extent
    end
  end
end
```

**Comment by mojavelinux** [comment] 2022-05-03 00:42
I have documented how to add a TOC per chapter using an extended converter. You can find the example code at the following location: https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/modules/extend/examples/pdf-converter-chapter-toc.rb This example, as well as numerous others, will be included in the documentation for Asciidoctor PDF 2.0.0 when it is released.

Since the rules for where to insert a "minitoc" can vary widely, as well as how that TOC should appear, I think this is best left up to an extended converter. If many users are in agreement that this should become part of this converter, we always have the option of shipping the converter with this logic included.

**Closed by mojavelinux** 2022-05-03 00:42 UTC
