### ISSUE TITLE
Icon fonts missing from PDF

### ISSUE THREAD

**Issue by aalmiray** [asciidoctor/asciidoctor-pdf#97] opened 2015-03-03 12:34 UTC
If `:icons: font` is applied to the document then icons go missing in the final PDF. Asciidoctor outputs the following warning

    asciidoctor: WARNING: conversion missing in backend pdf for inline_image

gradle 2.3
asciidoctor 1.5.2
asciidoctorj-pdf 1.5.0-alpha.6

**Comment by DavidGamba** [comment] 2015-03-03 16:47
Take a look at: https://github.com/asciidoctor/asciidoctor-pdf/issues/9

**Comment by madmas** [comment] 2015-03-26 13:34
I thinke it's also related to #15  and could maybe be solved with PR #90

**Comment by mojavelinux** [comment] 2015-03-30 18:15
Indeed. This seems like good Hackergarten material to me :)

**Comment by mojavelinux** [comment] 2015-05-17 05:59
@madmas this is only partially solved by #90. We still need to parse the inline image. Once we do that, then we can delegate to the `icon` method to draw the font-based icon. I'd say this is really a duplicate of #9.

**Closed** 2015-06-05 05:33 UTC
Labels: duplicate, in progress

**Comment by mojavelinux** [comment] 2015-06-05 05:36
I just got inline icon macros working. What's more, you can use one of 4 icon sets.

Here's a full example:

```
Available now at icon:amazon@pf[].
```

That reads "the amazon icon in the pf (payment font) icon set". You can also write it as:

```
Available now at icon:amazon[set=pf].
```

In addition to the sizes supported in the HTML backend (lg, 1x, 2x, etc), you can enter any relative value in the size attribute (e.g., 1.5em, 150%, etc).

```
icon:android[size=40em]
```

You can also set the icon set globally.

```
= Icons
:icon-set: octicon

icon:alert[] Don't miss this!
```

We don't yet support any way to color the icon.

**Comment by anandchida** [comment] 2015-10-13 18:51
I'm on Fedora 22 x86_64 with

asciidoctor -v
Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.9 using Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

I do not see the Font Awesome icons in the PDF but I do see them in HTML.

I've declared :icon-set: fa and use font like this icon:android[size=2x] this works in HTML but in PDF I see text [android]

I generate PDF using 
asciidoctor-pdf asciidoctor-example.adoc

I'm sure I'm missing something here and any help is appreciated! Thank you for working on such an awesome project! This has made documentation so easy :)

**Comment by mojavelinux** [comment] 2015-10-13 21:13
Can you try?

```
asciidoctor-pdf -a icons=font asciidoctor-example.adoc
```

**Comment by anandchida** [comment] 2015-10-14 04:13
This worked like a charm for both icons and admonition icons.  Thank you! 

I'ne sent in a pull request to improve some documentation around this.

**Comment by mojavelinux** [comment] 2015-10-14 09:16
:+1:

**Comment by jfthuong** [comment] 2019-06-25 02:19
> I just got inline icon macros working. What's more, you can use one of 4 icon sets.
> 
> * fa - Font Awesome
> * octicon - Octicons
> * fi - Foundation icons
> * pf - Payment font
> 
> Here's a full example:
> 
> ```
> Available now at icon:amazon@pf[].
> ```

@mojavelinux  Does it also work on **asciidoctor** generating HTML?

I can't make it work (I tried with `octicon`, with/without `:icon-set:`).

Thanks

**Comment by mojavelinux** [comment] 2019-06-25 02:21
No, this is a feature specific to PDF.

There's some discussion about adding it for HTML in this PR: https://github.com/asciidoctor/asciidoctor/pull/1801, but there are technical challenges yet unsolved.

**Comment by jfthuong** [comment] 2019-06-25 02:26
I'm amazed by your quick answer.

I have been in this PR and that's when I tried the icon-set **Feather**.

Looking forward the integration... and by the way, a big :+1: for the great work on **Ascidoctor**: this really revolutionized my way of doing technical documentation and presentations (+ Reveal.js) since I have discovered it in January 2018.

**Comment by mojavelinux** [comment] 2019-06-25 02:29
Thanks!

**Comment by jfthuong** [comment] 2019-06-25 03:29
> Could we use multiple icon sets in a single document?

To answer a super old question: yes, you can

For example:
```
:icons: font
...
icon:mortar-board[] icon:settings@octicon[]
```
