### ISSUE TITLE
Non-Latin internal cross references doesn't work

### ISSUE THREAD

**Issue by RazrFalcon** [asciidoctor/asciidoctor-pdf#833] opened 2017-07-12 19:33 UTC
Example:

```
= Document Title
Doc Writer <doc@example.com>
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing

== Заголовок

// This works.

<<Title>>

== Title

// This don't.

<<Заголовок>>
```

The `<<Заголовок>>` will be rendered as `[Заголовок]`, blue and hovered cursor will change, but clicking would not work.

References with Latin names works fine.

**Comment by mojavelinux** [comment] 2017-07-12 19:57
Can you confirm which version of Asciidoctor PDF you are using. This should have been fixed by #481.

```
asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.15 using Asciidoctor 1.5.6 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by RazrFalcon** [comment] 2017-07-12 20:02
```
Asciidoctor PDF 1.5.0.alpha.15 using Asciidoctor 1.5.6 [http://asciidoctor.org]
Runtime Environment (ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

```

**Comment by mojavelinux** [comment] 2017-07-12 20:17
I think I know what it is. This is a natural cross reference, and I bet the
case comparison isn't working because it's Ruby 2.1. International case
comparison wasn't introduced until 2.4. I'll retest on Ruby 2.1 and confirm
whether there's a workaround.

**Comment by mojavelinux** [comment] 2017-07-12 20:48
Yep, the issue is that downcase in Ruby 2.1 doesn't lowercase the non-latin characters in, which is necessary for the natural cross reference to be recognized.

Here's one way to work around it.

1. Install the unicode gem

```
$ gem install unicode
```

2. Create a script unicode-downcase.rb to route downcase to use Unicode.downcase:

```ruby
require 'unicode'

class String
  remove_method :downcase
  def downcase
    Unicode.downcase self
   end
end
```

3. Load this script when invoking asciidoctor-pdf:

```
$ asciidoctor-pdf -r ./unicode-downcase.rb doc.adoc
```

**Comment by mojavelinux** [comment] 2017-07-12 20:52
The other solution is to use explicit IDs instead of natural cross references. In your case:

```
[#Заголовок]
== Заголовок

<<Title>>

== Title

<<Заголовок>>
```

Technically a number is not a valid start character for an ID, though HTML allows it. See https://github.com/asciidoctor/asciidoctor/issues/2117.

**Comment by mojavelinux** [comment] 2017-07-12 20:54
Since Ruby solved this issue, I'm more inclined to recommend upgrading to 2.4 than trying to patch Asciidoctor. If Ruby didn't solve it, then I'd say it is our responsibility.

**Comment by RazrFalcon** [comment] 2017-07-13 07:30
>Technically a number is not a valid start character for an ID

`З` is not a `3`. [It's cyrillic `Z`](https://en.wikipedia.org/wiki/Ze_(Cyrillic)). 

> I'm more inclined to recommend upgrading to 2.4

I've managed to update to 2.4 and references is working now.

The problem is that there no warning about using an outdated ruby, which will be helpfull.

Also, in Gentoo Linux stable ruby is `2.2.6`. And `2.3.3` in Debian 9. So `2.4` is not an option.

**Comment by mojavelinux** [comment] 2017-07-13 09:31
> `З` is not a `3`. It's cyrillic `Z`.

Oops! My mistake.

> The problem is that there no warning about using an outdated ruby, which will be helpfull.

Asciidoctor 1.5.6 brought the infrastructure necessary to be able to validate these types of cross references. As we move forward, those warnings will make their way into the downstream projects like Asciidoctor PDF. So we're moving towards providing that type of feedback.

I don't think warning about what version of Ruby you have is the right thing to do. But we certainly should be responsible for warning about cross references.

**Comment by mojavelinux** [comment] 2017-07-13 09:37
OMG, I totally forgot to mention a new feature in Asciidoctor 1.5.6 that would have helped you in this case. While we can't be absolutely sure about broken references just yet, for now we added this specific warning behind the verbose flag.

```
$ asciidoctor-pdf -v doc.adoc
```

Then you will see the new warning.

```
asciidoctor: WARNING: invalid reference: Заголовок
```

**Comment by mojavelinux** [comment] 2017-07-13 09:38
We want to be able to take away the requirement for using the verbose flag, but first we need to be able to catalog every reference and we are still missing a few.

**Comment by RazrFalcon** [comment] 2017-07-13 09:55
>invalid reference: Заголовок

Sadly, it doesn't explain why it is invalid.

>I don't think warning about what version of Ruby you have is the right thing to do

I don't know how Ruby infrastructure works, so that's was only my suggestion.

**Comment by mojavelinux** [comment] 2017-07-14 00:37
That's all the information that the processor is going to provide. Additional information should come from the tooling layer, for example an IDE.

**Closed by mojavelinux** 2017-07-14 00:37 UTC
