### ISSUE TITLE
Wrong page number ordering in index

### ISSUE THREAD

**Issue by PascalLeMerrer** [asciidoctor/asciidoctor-pdf#1943] opened 2021-07-03 09:34 UTC
In the generated index, the order of page numbers is wrong when some contains 2 digits and others 3 digits.
For example:

> P
> pattern matching, 184, 187, 196, 196, 42, 53, 57, 72

I was expecting:

> P
> pattern matching, 42, 53, 57, 72, 184, 187, 196, 196

I'm using Asciidoctor PDF 1.6.0 and Asciidoctor 2.0.15

**Comment by mojavelinux** [comment] 2021-07-04 03:36
This is a duplicate of #1657 and has already been fixed in the main branch. I don't have any plans to backport this to 1.6.x, so it will become available once the first 2.0.x release is published.

**Closed by mojavelinux** 2021-07-04 03:36 UTC
