### ISSUE TITLE
Asciidoctor-PDF Failure: undefined method `checksum' for class `TTFunk::Subset::Base' (NameError)

### ISSUE THREAD

**Issue by coxjacob** [asciidoctor/asciidoctor-pdf#1463] opened 2020-01-05 08:01 UTC
I tried to install Asciidoctor-PDF on Ubuntu 18.04.3 and  Ubuntu 19.10.  Both VMs were new installs. In both cases, I get the same failure. I installed asciidoctor-pdf as follows: 

```
sudo get-install ruby
sudo gem install asciidoctor-pdf --pre
asciidoctor-pdf -v
```
I've also attempted to install asciidoctor first before installing askiidoctor-pdf with these commands:

```
$ sudo apt-get install -y asciidoctor
$ gem install asciidoctor
sudo gem install asciidoctor-pdf --pre
asciidoctor-pdf -v
```

In all cases, the result produces the following error log: 

```
       jcox@ubuntu:~$ asciidoctor-pdf -v
       Traceback (most recent call last): 

        10: from /usr/local/bin/asciidoctor-pdf:23:in `<main>'

	 9: from /usr/local/bin/asciidoctor-pdf:23:in `load'

	 8: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.beta.8/bin/asciidoctor-pdf:5:in `<top (required)>'

	 7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'

	 6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'

	 5: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf.rb:5:in `<top (required)>'

	 4: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf.rb:5:in `require_relative'

	 3: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf/converter.rb:4:in `<top (required)>'

	 2: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf/converter.rb:4:in `require_relative'

	 1: from /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf/ext/ttfunk.rb:3:in <top (required)>

           /var/lib/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.beta.8/lib/asciidoctor/pdf/ext/ttfunk.rb:4:in 
          <class:Base>': undefined method `checksum' for class `TTFunk::Subset::Base' (NameError)` 
```
asciidoctor still works fine. 

```
jcox@ubuntu:~$ asciidoctor -v
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```
Including my Ruby Version: 
```
jcox@ubuntu:~$ ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
```

I'm at a loss for how to fix it.

**Comment by mojavelinux** [comment] 2020-01-05 08:07
This is a duplicate of #1461, which was reported earlier today. It will be fixed in the next release. In the meantime, you can downgrade ttfunk to 1.5.1, if possible.

**Closed by mojavelinux** 2020-01-05 08:07 UTC

**Comment by coxjacob** [comment] 2020-01-06 02:15
Thank you. Downgrading worked!

**Comment by dusicong** [comment] 2020-01-06 09:41
same problem happens to me. I read the solution, but can't understand. could you help please?

can you tell me how to downgrade ttfunk to v1.5.1?
I changed ttfunk.rb of v1.5.0 beta 8 to ttfunk.rb of v1.5.0 beta7 or v1.5.0 beta6, and neighter of them works. And I found v1.5.0.rc.1 even though it seems can not be used, but is that the v1.5.1?
Thank you in advance.

**Comment by mojavelinux** [comment] 2020-01-06 10:21
Just be patient. I'll be releasing rc.1 shortly.

**Comment by dusicong** [comment] 2020-01-07 05:46
I cloned to the very right now version, and the problem solved.
Thanks anyway.
