### ISSUE TITLE
Allow to define the text background and border on inline marks (with a custom role)

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-pdf#1237] opened 2019-08-29 20:51 UTC
Consider the following AsciiDoc document:

```adoc
[.hello]#bonjour#
```

In the theme file, I want to be able to define the background color:

```yml
role:
  hello:
    background-color: #f0f0f0
```

It should also be possible to configure the border:

* `border-radius`
* `border-offset`
* `border-width`
* `border-color`

**Comment by mojavelinux** [comment] 2019-08-29 21:22
This is a duplicate of #1223.

**Comment by Mogztter** [comment] 2019-08-30 05:45
Ooops, sorry about that 😅

**Comment by mojavelinux** [comment] 2019-08-30 05:50
No worries. You certainly worded it more clearly.

**Closed** 2019-08-30 09:19 UTC
Labels: duplicate
