### ISSUE TITLE
Left Margins shrink from page to page

### ISSUE THREAD

**Issue by BrianEmberling** [asciidoctor/asciidoctor-pdf#1949] opened 2021-07-19 05:52 UTC
I have a small test case where depending on the exact vertical alignment, the left margin starts to shrink on then 2nd and 3rd page.  I'm using the default theme (only overriding page size to "letter"). 

asciidoctor-pdf -a pdf-stylesdir=./ -a pdf-style=bug bug.adoc -o out.pdf

I couldn't debug any further (not a software guy). At this point, nearly anything I delete or any addition/removal of lines can make the bug disappear.  I'm running version 1.60 on windows 10. 
(asciidoctor 2.0.15, prawn 2.4.0, ruby27)
[bug.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/6838275/bug.zip)

Attached in a zip:
bug.adoc - the input file
bug-theme.yml  - just sets "letter" size
out.pdf - example output showing shrinking margins
build.bat - run command in windows

**Comment by mojavelinux** [comment] 2021-07-21 04:47
This is the same issue as #1735 and is caused by https://github.com/prawnpdf/prawn/issues/1121. This is fixed in the main branch. I don't currently have any plans to backport this to 1.6.x.

**Closed by mojavelinux** 2021-07-21 04:47 UTC

**Comment by mojavelinux** [comment] 2021-07-21 04:54
For completeness, I will add a test case based on this particular example. The existing test case is for a slightly different scenario and I want to make sure this scenario is covered to avoid any regression.
