### ISSUE TITLE
More consistency in caption side configurability

### ISSUE THREAD

**Issue by odrotbohm** [asciidoctor/asciidoctor-pdf#2087] opened 2022-04-26 14:35 UTC
The defaults for caption sides are currently as follows:

* Code blocks: top
* Figures: bottom
* Tables: top

Tables seem to have recently seen a `caption-side` configuration property added to be able to flip the caption to the bottom. I can see that code blocks default to top, as a callout list would have to go right below the block.

It would be nice to be able to define the property for both figures and code blocks, too. The former would allow me to consistently switch to top captions throughout the entire document, the latter would allow switching them all to bottom in case I would either accept how the arrangement with callout numbers look or just avoid them in the first place.

**Comment by mojavelinux** [comment] 2022-04-26 22:15
This is a duplicate (albeit more generic) of #1730.

It's not a terribly difficult thing to implement now, though we will lose the ability to prevent the caption from being orphaned since that would require even more look-ahead checking.

**Comment by mojavelinux** [comment] 2022-05-03 00:48
> It would be nice to be able to define the property for both figures and code blocks, too.

The converter now supports placing the caption on top of images thanks to the fix for #2115.

**Comment by mojavelinux** [comment] 2022-05-03 00:50
What remains has become a duplicate of / covered by #1730.

**Closed by mojavelinux** 2022-05-03 00:50 UTC
Labels: duplicate

**Comment by odrotbohm** [comment] 2022-05-03 06:32
Thanks, Dan!
