### ISSUE TITLE
Cross-document links

### ISSUE THREAD

**Issue by gAmUssA** [asciidoctor/asciidoctor-pdf#83] opened 2015-01-10 00:27 UTC
What's is correct format of inter-document references should be used so it would work in pdf?

**Comment by mojavelinux** [comment] 2015-01-10 00:34
You should use the inter-document reference syntax from Asciidoctor and we'll make sure to get it working in asciidoctor-pdf. We definitely don't want to compromise the integrity of the input by doing something different.

In general we have a problem with references in Asciidoctor PDF that we need to solve that should take care of this as well. See #56.

**Comment by gAmUssA** [comment] 2015-01-10 00:40
@mojavelinux TOC links work fine. Custom anchors `[[anchor]]` don't resolve with `<<anchor,my text>>`

**Comment by mojavelinux** [comment] 2015-01-10 01:06
Correct. Basically, links only work to sections at the moment. We're not yet creating PDF anchors for anything inline or for blocks. It's doable, but it just got missed the first time around.

**Comment by gAmUssA** [comment] 2015-01-12 21:36
@mojavelinux is there any way refer particular "chapter" without custom anchor?

I guess it worth to mentioned that we use `asciidoc-maven-plugin`

**Comment by mojavelinux** [comment] 2015-01-13 02:41
References to a chapter (because it's a section) should work. In other words, `<<chapter_13,Chapter 13>>`.

(Notice I said *should* work. If not, we need to fix it.)

**Comment by mojavelinux** [comment] 2015-01-13 02:43
Another way to state it is that we should add an example to https://github.com/asciidoctor/asciidoctor-pdf/blob/master/examples/chronicles.adoc so that we can see it in action with a tangible example.

...that is, until we have proper tests. See #37 :)

**Comment by plaindocs** [comment] 2015-02-16 15:06
@mojavelinux when you say chapter / sections should work, what is the syntax exactly? 
----
<<chapter_13,Chapter 13>>

...

== Chapter 13
----

or

----
<<my_chapter, Chapter 13>>

...

== My Chapter

NOTE: This happens to be chapter 13
----

Neither works for me.

**Comment by derkork** [comment] 2015-05-12 15:00
What exactly is the "ready" label on this issue implying? That a fix for this is ready?

**Comment by mojavelinux** [comment] 2015-05-12 22:01
ready means it's ready to work on. The design is decided. It's added by an
external tool I've been using to a schedule tasks.

We're going to be putting together a legend for labels used across the
Asciidoctor soon, though I'm still experimenting with names.

**Comment by derkork** [comment] 2015-05-13 06:55
Ah ok great.  Thanks for the explanation!

**Comment by mojavelinux** [comment] 2015-05-13 08:54
I should have this one done by the end of the week (in fact, it's the next coding issue I'm going to tackle).

**Comment by mojavelinux** [comment] 2015-05-13 08:56
Actually, this issue is too vague. I'll be addressing #110. I'll then clarify where we stand once that is done.

**Comment by mojavelinux** [comment] 2015-05-26 01:00
This was resolved by https://github.com/asciidoctor/asciidoctor-pdf/commit/fda6cfb09921af25263675885c2a68005223f521 as part of the fix for #110.

**Closed by mojavelinux** 2015-05-26 01:00 UTC
Labels: bug, ready

**Comment by gAmUssA** [comment] 2015-05-27 01:51
@mojavelinux you're da man! is it exposed to asciidoctor pdf for java yet?

**Comment by mojavelinux** [comment] 2015-05-27 06:15
I'll be doing another alpha this week, then I'll let Robert know to push out a new asciidoctorj-pdf jar. We set it up so that we can release individual components separately.

**Comment by PaulMougel** [comment] 2015-08-16 09:03
Just ran into this issue. I can confirm that cross-documents links now work with the newest published gem, thank you very much!

```
$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.9 using Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

To upgrade the gem: `gem install --pre asciidoctor-pdf`.

**Comment by mojavelinux** [comment] 2015-08-16 09:46
:+1:
