### ISSUE TITLE
Bottom edge of an imported code block can bleed over without text to a new page

### ISSUE THREAD

**Issue by handcraftsman** [asciidoctor/asciidoctor-pdf#482] opened 2016-07-20 18:20 UTC
![bleedover](https://cloud.githubusercontent.com/assets/234664/16997782/887eae1a-4e7c-11e6-9073-5d6bf27c7410.png)

**Comment by mojavelinux** [comment] 2016-08-08 07:25
This appears to be a duplicate of #361.

**Closed** 2016-08-13 09:24 UTC
Labels: bug, duplicate
