### ISSUE TITLE
Basic format of phrases.

### ISSUE THREAD

**Issue by github-login** [asciidoctor/asciidoctor-pdf#817] opened 2017-05-28 16:04 UTC
Asciidoctor 1.5.4 [http://asciidoctor.org]

Asciidoctor PDF 1.5.0.alpha.15 using Asciidoctor 1.5.4 [http://asciidoctor.org]

```
#highlight me# -> don't work in PDF 

[highlight]#highlight me# -> don't work in both PDF and HTML 

[underline]#underline me# -> works in both PDF and HTML.

[color]#color me# -> don't work in PDF
```
I hope highlight or color is an easy fix because I need either one of them.

**Comment by JBR69** [comment] 2017-05-29 14:47
Hi,

for ```underline``` and ```color```, you can see my proposition in the ticket #652

Jérôme

**Comment by mojavelinux** [comment] 2017-05-29 22:34
We don't currently have support for custom roles on phrases, or highlighted text for that matter. This is a duplicate of #376, which is also being discussed in the #350 pull request.

**Comment by github-login** [comment] 2017-05-30 00:01
Thank you. So "underline" is considered non-custom and is implemented ? What is the criteria ? 

This is inconsistency between asciidoctor and asciidoctor-pdf !

**Comment by mojavelinux** [comment] 2017-05-30 01:42
The goal is to close that gap. Some things are easy to implement (like
underline), some are hard. Step by step.

**Comment by mojavelinux** [comment] 2019-09-01 05:39
This has been covered by various other issues and has since been resolved.

Note that to support a custom role, like `red`, you must define it in the theme file as follows:

```yml
extends: default
role:
  red:
    font-color: #ff0000
```

**Closed by mojavelinux** 2019-09-01 05:39 UTC
Labels: duplicate
