### ISSUE TITLE
Math export

### ISSUE THREAD

**Issue by krampenschiesser** [asciidoctor/asciidoctor-pdf#246] opened 2015-06-27 11:06 UTC
Just discovered that asciidoctor has math(jax) support now :)
Can we expect any export functionality so that we have rendered math formulas in the pdf's?
Or is it html only because of mathjax(javascript)?

**Comment by mojavelinux** [comment] 2015-07-02 08:43
This is definitely in cards. This issue is a duplicate of #45.

I have been able to get Math to embed correctly using the Mathoid extension in the extensions lab. https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/mathoid-treeprocessor.rb. However, I don't really expect anyone else to be able to use it just yet because it's not documented. That's one strategy to getting this to work. We're trying others as well.

**Comment by mojavelinux** [comment] 2015-07-02 08:44
Please follow-up on #45.

**Closed by mojavelinux** 2015-07-02 08:44 UTC
Labels: duplicate
