### ISSUE TITLE
Wrong color in output

### ISSUE THREAD

**Issue by tgeek77** [asciidoctor/asciidoctor-pdf#1022] opened 2019-04-10 12:08 UTC
Hi all, this is a fantastic tool, but I found a rather annoying issue.

My asciidoc code:

```
+
`[blue]*kubeadm init --cri-socket=/var/run/crio/crio.sock \*`
{nbsp} +
`[blue]*--pod-network-cidr=10.244.0.0/16*`
+
```

In asciidoctor html export, this appears as bold, blue, monospace text. This is correct.
In the asciidoctor-pdf export, it appears as bold, **red**, monospace text.

**Comment by mojavelinux** [comment] 2019-04-10 20:21
Asciidoctor PDF does not currently support custom and built-in roles (and thus doesn't support explicitly colorizing text). This is a duplicate of #368, #459, and #817.

(The red color is coming from the theme).

**Comment by mojavelinux** [comment] 2019-07-30 10:04
In 1.5.0.beta.2, you'll be able to define the font properties for a role in your theme. For example:

```
role:
  blue:
    font-color: 0000ff
```

**Closed** 2019-07-30 10:05 UTC
Labels: duplicate
