### ISSUE TITLE
table head_background_color is not applied to header column

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#695] opened 2016-12-12 11:28 UTC
I have the following in default theme:

```
table:
  background_color: $page_background_color
  head_background_color: f0f0f0
  head_font_style: bold
  foot_background_color: f0f0f0
  border_color: dddddd
  border_width: $base_border_width
```
which renders ok for `[options="header"]`

But for `[cols="h, 1"] I get only text to be bold, background is not applied:

```
[cols="h,1"]
|===
|cell1| value1
|cell2| value2
|cell3| value3
|===
```
![adoc-table-col-heading](https://cloud.githubusercontent.com/assets/234774/21097746/210fdd2c-c077-11e6-9a9d-f2dfd7d06ea2.png)

**Comment by mojavelinux** [comment] 2016-12-13 00:49
This is a duplicate of #239, which I plan to fix for the upcoming version.

**Comment by mojavelinux** [comment] 2016-12-13 00:53
Btw, you can style the header cells in the table body. #239 is just about inheritance.

See the table_header_cell key under https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#table.

**Closed** 2016-12-13 00:53 UTC
Labels: duplicate
