### ISSUE TITLE
Issue with icons and underlines in preserved line breaks

### ISSUE THREAD

**Issue by rmpestano** [asciidoctor/asciidoctor-pdf#485] opened 2016-07-31 17:14 UTC
Hi,

I'm facing an issue only with PDF backend where icons are failing to render in pdf backend, here is sample adoc:

```
:icons: font
:hardbreaks: 

== Issue with icons and underline in preserved line breaks

icon:github[link=https://github.com/asciidoctor, role="external", window="_blank", alt="Ascidoctor"]
any text here ending with underline will throw `Failed to parse formatted text`_
```

throws this error while rendering the pdf:

```
Failed to parse formatted text: <a href="https://github.com/asciidoctor"><font name="fa"></font></a><br> any text here ending with underline will throw `Failed to parse formatted text`</em>

```

here is rendered pdf:

![issue](https://cloud.githubusercontent.com/assets/1592273/17278031/411c20ac-5728-11e6-8626-082054a8e05b.png)

The issue happens whenever I use a icon and preserve linebreak (using harbreaks or + sign to for line break) and in line below there is a word ending with underline.

In html backend the underline is not rendered.

**Comment by mojavelinux** [comment] 2016-08-01 22:44
This is a complication that is caused by the substitution order. It does affect the HTML output too, it just isn't as apparent (since HTML is much more forgiving). The problem is that the underscore in `_blank` and the trailing underscore are forming a pair that is translated to `<em>blank...</em>`. The first `<em>` gets swept away in the attribute value, leaving an unmatched closing tag.

The short-term solution to this problem is to escape the underscore in `_blank`, either as:

    window="_blank"

or

    :window-blank: _blank
    ...
    window="{window-blank}"

You only need to do this when the underscore forms an unexpected pair.

The long-term solution is to switch to proper inline parsing so that substitution are contextual (in order words, a pair would never be formed between an attribute value and normal content).

**Comment by rmpestano** [comment] 2016-08-02 02:51
```window="\_blank"``` just works, thanks!

should we let this open for the long term solution?

**Comment by mojavelinux** [comment] 2016-08-02 04:14
For now, we may handle this as a documentation issue. I've mentioned in the documentation that URLs often have to be escaped. However, what the documentation doesn't mention is that formatted text can get matched in other unexpected places such as in attribute values for inline macros. Perhaps we should proceed by opening an issue in asciidoctor.org to add a warning to be aware that formatting can sometimes be applied where it isn't expected and what to do about it.

**Closed** 2022-06-02 08:39 UTC
Labels: documentation
