### ISSUE TITLE
Theming only partially works for an Example block spanning multiple pages

### ISSUE THREAD

**Issue by tmichett** [asciidoctor/asciidoctor-pdf#1981] opened 2021-10-30 01:29 UTC
When attempting to provide styles on the **example** portion of the document, the theming doesn't render correctly for the PDFs when the example flows across multiple pages. It actually runs the example theming through the bottom page margins and then stops.

Code (source) boxes on the other hand do exactly what is expected and it allows the code box to honor margins and be split across the pages.

```
code:
  font_color: $base_font_color
  font_family: $literal_font_family
  font_size: ceil($base_font_size * 0.7)
  #font_size: ceil($base_font_size)
  padding: $code_font_size
  line_height: 1.25
  background_color: f5f5f5
  border_color: cccccc
  border_radius: $base_border_radius
  border_width: 0.75

example:
  border_color: #ff8000
  border_radius: $base_border_radius
  border_width: 0.75
  background_color: #ffffc2
  # FIXME reenable margin bottom once margin collapsing is implemented
  padding: $code_font_siz
```

![Example-not-spanning-kills-margin](https://user-images.githubusercontent.com/12944787/139515554-614b3220-6413-4328-a10b-a65cc8fee923.png)
e

**Comment by mojavelinux** [comment] 2021-10-30 03:12
Please indicate which version of Asciidoctor PDF you are using.

**Comment by ebousse** [comment] 2022-02-21 12:32
Rather similar problem here with asciidoctor-pdf 1.6.2.

I have the following bit in my theme:
```yaml
example:
  background-color: fcf5c6
```

I compile with `-a media=prepress` and `-d book`, which means odd and even pages are treated differently.

Here is an example of output:
![asciidoctorpb](https://user-images.githubusercontent.com/5868014/154955373-38189489-25dd-47f4-ba60-ef6a38c02077.png)

We can see that the example block that should be spanning from page 10 to the top of page 11 is not correct: the yellow background that should be painted at the top of page 11 is instead drawn at the top of page 12. Essentially, the example block is drawn as if page 12 was following page 10, while it's not.

**Comment by ebousse** [comment] 2022-02-21 16:41
Strangely I made my problem disappear by changing the font of my examples:

```yaml

font:
  catalog:
    merge: true
    Roboto:
      normal: roboto-normal.ttf
      italic: roboto-italic.ttf
      bold: roboto-bold.ttf
      bold_italic: roboto-bold_italic.ttf

example:
  font-family: Roboto
  background-color: fcf5c6
```

with `Roboto` installed as explain in the docs.

But it's probably just a coincidence…

**Comment by mojavelinux** [comment] 2022-03-01 01:39
I'm working on rewriting all the code for unbreakable blocks so that it always draws the borders and background correct. This fix will be included in the upcoming Asciidoctor PDF 2. The current logic cannot be fixed, it must be replaced.

**Comment by mojavelinux** [comment] 2022-03-01 01:57
It would be helpful if you could provide a reproducible example in source form so that I can test it with the new code. I can't do anything with images.

**Comment by ebousse** [comment] 2022-03-01 09:06
Of course, I understand. Strangely since I changed my document quite a lot, I now have a hard time reproducing this. I'll try pulling an older version.

**Comment by mojavelinux** [comment] 2022-03-01 09:11
Thanks! I'd really like to verify that the new code puts this behind us.

**Comment by ebousse** [comment] 2022-03-01 10:26
OK I've reproduced it, but sorry in advance it's a book rather long to compile (~50mb, ~200 pages).

My environment:
```
Asciidoctor PDF 1.6.2 using Asciidoctor 2.0.17 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```
Instructions:
- Get the sources here: https://filesender.renater.fr/?s=download&token=91a08e09-ef45-4598-9075-5eee464dd3fb
- Run this command: 
```
asciidoctor-pdf -r asciidoctor-diagram -r asciidoctor-mathematical -a 'revdate=01/03/2022, 13:14' -a lang=fr -a pdf-themesdir=resources/pdfthemes -a pdf-theme=mytheme -a 'pdf-fontsdir=resources/pdffonts;GEM_FONTS_DIR' -a media=prepress -d book -o public/book/tmp.pdf public/book/single-page-M2MIAGE.adoc
```

Then look at pages 50-52 to observe the problem.

It's probably possible to reproduce it with a smaller document, but things move around each time I remove stuff and the problem often disappears this way.

**Comment by mojavelinux** [comment] 2022-03-01 11:07
Thanks for sharing that.

Now that I look at it, I realize this is likely a different issue. You're using unbreakable blocks that span more than one page inside of unbreakable blocks. This converter is simply not equipped to handle that situation. I'm going to try to see if I can get the converter to go a bit further than it currently does, but there are limits to what I can do with it. The situation just gets entirely too complex and state ends up stepping on other state. This is a key reason why we must exploring other solutions for generating PDF from AsciiDoc. We are well beyond the limits of what I can make this PDF generator library do.

**Comment by ebousse** [comment] 2022-03-01 11:32
I see, thanks for the explanations! Just out of curiosity, why does the faulty background "skips" one page and goes from page 50 to page 52 without impacting page 51? Is this because I am using `prepress`?

**Comment by mojavelinux** [comment] 2022-03-01 11:41
The document certainly does give me a lot of test cases, though. So that's a very good thing.

> why does the faulty background "skips" one page and goes from page 50 to page 52 without impacting page 51

It's because the way a background is drawn, and the extend for that background is computed, is incredibly complex. If something is off somewhere, it can end up advancing or going back to the wrong page and thus starting from the wrong spot. It has nothing really to do with the settings on the document. The bug can manifest in a large number of situations.

With the new code, it should not make those mistakes anymore. However, if something I don't anticipate mutates the state, such as which page we are on...it could cause the bug to reemerge. The only thing I can do is keep creating tests and hoping that I have considered all the possibilities that nested blocks introduce.

**Comment by mojavelinux** [comment] 2022-03-01 11:45
I want to emphasize again that this PDF library was never intended to be used for what we are using it for. We started humbly with a few simple AsciiDoc documents and kept building on it for a decade. I try hard to keep the complexity manageable, but we cannot get avoid the fact that the library only offers us primitives and an write ahead model. To compute the area a block takes, we have to create a second PDF document, reconfigure it exactly the same way as the original, write into it and see what happened. It's kind of nuts.

**Comment by ebousse** [comment] 2022-03-01 11:49
> The document certainly does give me a lot of test cases, though. So that's a very good thing.

Glad to help :). Just so that you know, the git repository of the document is public and can be found here: https://gitlab.univ-nantes.fr/naomod/testing/course. For reproducing the problem, I rolled back to commit `ac1763adda3197265890fe9e84b2434ab9f2ae3b`. The repo is used both for producing a website (https://naomod.univ-nantes.io/testing/course/book/) and for producing PDFs of the very same content.

> It has nothing really to do with the settings on the document. The bug can manifest in a wide variety of situations, which often only show up in very complex documents.

Noted, thanks.

> I want to emphasize again that this PDF library was never intended to be used for what we are using it for. 

I sortof understood this aspect of the project while going over some discussions in the bug tracker. It's really impressive what you managed to accomplish despite this situation, as we can really obtain nice results with the current version! And the theming works very well.

**Comment by mojavelinux** [comment] 2022-03-02 03:54
I have very good news to share with you. Thanks to the plethora of edge cases your book provided, I think I was able to get down to the problem, as well as solve other problems I had never seen before. I'll now be able to create tests for all of those cases. So we're in better shape than I had originally thought.

To address the specific issue at hand, it turned out to be a bug in the converter after all. It was inserting an extra page instead of advancing to the next page, which was pushing the background to the next page and drawing into a blank page.

**Comment by mojavelinux** [comment] 2022-03-02 07:40
Of the best test cases come from real world documents. It's quite difficult to create mock content with any amount of complexity. Over the years, I've heavily relied on testing long books or manuals. It's amazing what I discover that way.

**Comment by mojavelinux** [comment] 2022-03-04 22:27
Addressing the initial issue, the screenshot shown is a clear sign that the PDF was produced using a version of Asciidoctor PDF older than 1.6. Therefore, I'm closing this issue as resolved.

In the future, an issue must be accompanied by a code snippet or the full content. Showing a screenshot of the output is not enough information for me to reproduce the issue and therefore is not actionable. I'm not going to spend my time trying to reverse engineer it anymore. I need a reproducible test case (in any form you can provide it) so that I can concentrate my time instead on fixing the problem.

**Closed by mojavelinux** 2022-03-04 22:27 UTC
