### ISSUE TITLE
Support for multiple backgrounds

### ISSUE THREAD

**Issue by pdorrestijn** [asciidoctor/asciidoctor-pdf#1913] opened 2021-04-15 14:04 UTC
I would like to be able to change the background image on a particular page (in the pdf).
For example by specifying in a page:
...
page-background-image: alternate-background-1.svg[] 
...

It would also be nice if the documentation clearly lists the restrictions regarding declaring stuff like title-page-background-image and page-background-image. For instance the fact that these particular attributes are completely ignored when declared after the document title.

**Comment by mojavelinux** [comment] 2021-04-15 18:14
This is essentially a duplicate of #1739 (as the discussion progressed). That issue explains the technical barrier we facing in order to implement this.

**Comment by mojavelinux** [comment] 2021-04-15 18:29
> It would also be nice if the documentation clearly lists the restrictions regarding declaring stuff like title-page-background-image and page-background-image.

You're welcome to propose a documentation update.

> For instance the fact that these particular attributes are completely ignored when declared after the document title.

It's pretty typical for any attribute that controls the converter to have to be defined in the AsciiDoc document header (or via the API). Nonetheless, I added a "Header Only" column to the theme-related attributes table to make this explicit.

And to be clear, they can be defined after the document title. Just not after the document **header**.

https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/theming-guide.adoc#theme-related-document-attributes

**Closed** 2021-06-03 15:38 UTC
Labels: duplicate
