### ISSUE TITLE
Specify unicode character in hexadecimal

### ISSUE THREAD

**Issue by antoyo** [asciidoctor/asciidoctor-pdf#604] opened 2016-10-02 00:20 UTC
Hello, the notation `&#xA9;` does not work with `asciidoctor-pdf`.
I get the following error:
```
Failed to parse formatted text: &#xA9;
```
Could you please fix this issue?
Thanks.

**Comment by mojavelinux** [comment] 2016-10-02 01:48
This is a known limitation at the moment. Please use the decimal form for
now as it will allow you to achieve the desired result. (There are reasons
why supporting the decimal form is easier in this converter).

**Comment by mojavelinux** [comment] 2016-10-02 01:49
Duplicate of #486.

**Closed by mojavelinux** 2016-10-02 01:49 UTC
