### ISSUE TITLE
Add configuration for PDF title page

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/asciidoctor-pdf#1006] opened 2019-02-26 18:28 UTC
I would love to see the ability to configure the title page a bit more.
Right now you are limited to title, subtitle and basically contributor and version info. 

In my case I would like to print the product and version number in a prominent place and add more style elements than a single logo and the background color/image. I've resorted to designing elaborate background images but all that they do could be achieved by giving us more control about how the title page works.

Can you expose more attributes/content of the actual document for use and give some options to generate a more intricate layout? My ideal thing would be something like this:

```
# Layout always needs to go on the bottom
title_page:
  content:
    logo:
      image: image:/some/image.png[pdfwidth=15%]
      align: left
      top: 5%
      left: 5%
    title:
      content: {title}
      font_size: 36
    product_name:
      content: {product_name}
      font_size: 24
    product_version:
      content: {product_version}
      font_size: 24
    authors:
      content: {authors}
      font_size: $brand_font_size
    revision:
      content: {product_number} {build_number} {build_date}
      font_size: $brand_font_size
    #render image on top of background color, specify X/Y pixel offset for display
    decoration_image:
      image: image:/path/to/image.(png|svg|jpg)[pdfwidth=X]
      align: right
      top: 30%
      left: 60%
  layout:
    $background_color
    #$background_image
    $logo
    $decoration_image
    #$title:$subtitle
    $title
    $subtitle
    $product_name
    $horizontal_rule
    $product_version
    $authors
    $revision
```
      
I hope you get the idea. I would love to be able to just expose all kinds of attributes and content from the input document to the processor so I can design it a bit more. Define some "PDF attribute" that uses some available attributes from the document and give me some way to get basic arrangement of these elements on the resulting page.

EDIT 2019-02-26:
With the HTML output we have SASS/CSS to do all kinds of things but the PDF output really is very limited at this point. At the same time this is one of the most asked for features for product documentation by enterprise customers and what they really care about (because you can "archive" it).

**Comment by r0ckarong** [comment] 2019-02-26 18:51
This is how good it can look:
![screenshot from 2019-02-26 19-47-22](https://user-images.githubusercontent.com/4920542/53438085-61b1d980-39ff-11e9-88a7-9ff572856bd5.png)

BUT!

1. The green product name and version needs to be forced in that location via an ifdef hack in each book title.
2. I can not (in any way that is documented) add a horizontal rule anywhere on this page 
3. The graphics for the background would be 1 SVG and the background color with a few bytes but since it's not possible to have multiple graphics on the title page I need to produce a 30KB background image. It's not much but it could be avoided so easily.

**Comment by r0ckarong** [comment] 2019-02-26 20:35
I just realized that `decoration` needs to ignore the page margins (or allow to set separate page margins for the title page, which would be better).

**Comment by rockyallen** [comment] 2019-04-06 23:15
I would like this flexibility as well, but can I suggest a different way of achieving it.
Create a new special section (similar to [preface]) called title-page, eg

````
[title-page]
== Ignored title text
image:logo.png[float="right"]

=== Release Conditions
Stuff here

[title_page_title]
{doctitle}

[title_page_author]
{author}

image::product.png[width="100mm"]

=== Security notice
Stuff here

<<<<
// reverse of title page
=== Release authority

A Manager [underline]#{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}#

=== Version history
|===
|Release |Date |Change
|1 |2018 |....
|===

<<<<
// Other preliminary content

toc::[]

List of tables

lot::[]

List of figures

lof::[]
````

* It contains arbitrary asciidoc so you have a lot of flexibility in design.
* All document attributes are available as normal, so no special mechanism is needed to expose them.
* The current theming would apply to the content, based on the block styles.
* HTML could interpret the same content, avoiding having to keep separate copies for HTML and PDF.

I realize this is letting formatting leak into the document content, but I think it is justified in this case.

**Comment by mojavelinux** [comment] 2019-04-07 08:47
I feel this is outside the scope of what Asciidoctor PDF should provide out of the box. But it's certainly something you could do by extending the converter. There are a thousand different ways you might want to customize the title page, and Asciidoctor PDF simply wasn't designed to provide that level of styling flexibility. While having the title page be an AsciiDoc document is an interesting idea, it's only going to lead to a lot more frustration by what it can't do. This is a rabbit hole, IMO.

I am going to be proposing a new strategy for PDF generation very soon that I think will allow you to do something like this. When that happens, I think customizing the title page should be done using some variation of docinfo.

**Comment by lurch** [comment] 2019-10-10 15:15
Have there been any changes in this area? Or is the title page still limited to just a logo, a title, and a version-string?  (I don't have the Ruby-skills to write any custom conversion code)

**Comment by mojavelinux** [comment] 2019-10-10 18:54
The only option at this point is to extend the converter. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#extending-the-converter

I'm not even sure at this point that we'll pursue this issue.

**Comment by catrin-whitehouse** [comment] 2019-12-04 10:25
It would be nice just to have a separate footer for the title page to distinguish it from the footer for the main document

**Comment by mojavelinux** [comment] 2019-12-31 01:43
This is really a duplicate of #66. I'm going to close this one to merge the two issues.

**Closed by mojavelinux** 2019-12-31 01:43 UTC
