### ISSUE TITLE
Header column shows in next column when spanning cells

### ISSUE THREAD

**Issue by 1marc1** [asciidoctor/asciidoctor-pdf#1944] opened 2021-07-05 13:08 UTC
First of all, thank you again to everyone for your hard work on the projects in the Asciidoctor ecosystem.

I have ran into something odd, which I haven't come across before and haven't been able to find any further information about. Forgive me if this has been reported before.

When I take [example 2 of the documentation](https://docs.asciidoctor.org/asciidoc/latest/tables/span-cells/#ex-span-rows) about spanning rows in a table and add options to specify I want the first column to be a header column, then the cell containing **Cell in column 2, row 3** shows up as a header cell.

```
[cols="1h,1",frame=all,grid=all]
|===
|Column 1, header row |Column 2, header row

.2+|This cell spans rows 2 and 3 because its specifier contains a span of `.2+`
|Cell in column 2, row 2

|Cell in column 2, row 3

|Cell in column 1, row 4
|Cell in column 2, row 4
|===
```

For HTML output, I have tested this with Asciidoctor 2.0.10 and 2.0.15. For PDF output I have tested this with Asciidoctor-PDF 1.5.3 and 1.6.0. In all four cases it gives the same result. I would have expected that **Cell in column 2, row 3** is not a header cell.

Here is an example PDF output of the above table.

![image](https://user-images.githubusercontent.com/18713538/124475761-6e237980-dde5-11eb-9b51-a1dafb6d75c3.png)

If I change `cols="1h,1"` to `cols="1,1"`, then the output is as expected:

![image](https://user-images.githubusercontent.com/18713538/124476101-cd818980-dde5-11eb-92e9-5269be88acc3.png)

Thank you for looking into this.

Marc.

**Comment by mojavelinux** [comment] 2021-07-06 06:22
This is a duplicate of https://github.com/asciidoctor/asciidoctor/issues/989 and is a current a limitation of Asciidoctor itself when using the rowspan feature on styled cells.

As a workaround, you can fix the problem by setting the style (in this case, `d`) directly on the table cell.

```
[cols="1h,1",frame=all,grid=all]
|===
|Column 1, header row |Column 2, header row

.2+|This cell spans rows 2 and 3 because its specifier contains a span of `.2+`
|Cell in column 2, row 2

d|Cell in column 2, row 3

|Cell in column 1, row 4
|Cell in column 2, row 4
|===
```

**Closed by mojavelinux** 2021-07-06 06:22 UTC

**Comment by 1marc1** [comment] 2021-07-06 12:25
Thank you. Apologies for the duplicate.
