### ISSUE TITLE
Long list item sequences in table cells break page layout

### ISSUE THREAD

**Issue by rohel01** [asciidoctor/asciidoctor-pdf#1655] opened 2020-04-21 16:12 UTC
Hello,

Technical documents usually contain  some kind of changelog where every modification of the document is summarized for each released issue. 

A sample changelog table is:

Issue | Date | Change record | Author
------- | ------- | ------------------- | ----------
0.1 | 19/04/2020 | Initial release | Alice
1.0 | 20/04/2020 | "..." | Bob

In the change record column, I typically list every comment identifier I took into account with a short description. So, this column often contains a list.

Across major revisions of technical documents, this list can become huge. I have noticed asciidoctor-pdf struggles to layout such changelog table: the cell content flows out from its cell boundaries to the bottom of the page and overlaps with the content of the next pages. See below image for an example

![listcell_overlap](https://user-images.githubusercontent.com/9367595/79886585-75857f80-83f9-11ea-836b-2cf585861676.png)

The source for this example
[sample.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/4511148/sample.txt)

I tried manually adding page breaks into the offending cells, with no success. 

I use asciidoctor/docker-asciidoctor to generate my documents.

> bash-5.0$ asciidoctor-pdf --version
> Asciidoctor PDF 1.5.0 using Asciidoctor 2.0.10 [https://asciidoctor.org]
> Runtime Environment (ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

**Comment by mojavelinux** [comment] 2020-04-21 19:23
This is a duplicate of #1623, which was resolved in master. I would consider back-porting it to the 1.5.x line.

That fix merely truncates the cell. A cell cannot be taller than a single page. That's because the PDF generator we use doesn't support splitting a cell across pages. This limitation is mentioned in the README. You'll have the split the cell manually my moving some of the content to another row until the cell fits on a single page.

**Comment by rohel01** [comment] 2020-04-24 12:55
Ok, thanks for the workaround.
I am using asciidoctor-docker and I am not tied to a particular version. I can test the fix as soon as an updated docker image is available.

**Closed** 2022-04-16 10:09 UTC
Labels: duplicate, v2.0.0
