### ISSUE TITLE
path to external pdf-file will be shown additionally to the linkname when media is set to print or prepress

### ISSUE THREAD

**Issue by heiwilOS** [asciidoctor/asciidoctor-pdf#1824] opened 2020-11-16 12:56 UTC
when creating pdf-files with containing links to external pdf-files like

`link:Dir\SubDir\File.pdf[Linkname]`

`[Dir\SubDir\File.pdf]` will be shown behind the linkname in pdf-file, which is an unnecessary information for the reader IMHO.

here the answer of mojavelinux to my request: 

> This behavior is activated when the media is set to print or prepress. If
> you don't want it to show, you can set media to screen (or don't set it at
> all).
>
> Otherwise, there is no way to disable this behavior. There is an attribute
> (show-link-uri) that activates this behavior when the media is screen. We
> could support the inverse (hide-link-uri) to deactivate it when media is
> not screen.

**Comment by mojavelinux** [comment] 2020-11-16 21:21
For some users, this additional information is desirable (to reveal the target of a link in a printed document). Other users prefer to keep it hidden. The propose here is to introduce the `hide-link-uri` to suppress this behavior when media is print or prepress.

**Comment by mojavelinux** [comment] 2022-06-11 08:11
It turns out this is a duplicate of #951. The request was implemented in Asciidoctor 1.6.2 and is also available in Asciidoctor PDF 2.

**Closed by mojavelinux** 2022-06-11 08:11 UTC
Labels: duplicate
