### ISSUE TITLE
Table cell background color

### ISSUE THREAD

**Issue by rhattersley** [asciidoctor/asciidoctor-pdf#86] opened 2015-01-15 12:42 UTC
The [technique described for asciidoctor](https://github.com/asciidoctor/asciidoctor/wiki/How-to-set-the-background-color-of-a-table-cell) doesn't work for asciidoctor-pdf.

**Comment by mojavelinux** [comment] 2019-08-30 00:03
Duplicate of #234.

**Closed** 2019-08-30 05:44 UTC
Labels: duplicate
