### ISSUE TITLE
Indexing appears to sort page numbers lexically not numberically

### ISSUE THREAD

**Issue by gregturn** [asciidoctor/asciidoctor-pdf#1675] opened 2020-05-03 18:45 UTC
I LOVE that asciidoctor-pdf has indexing. I've been building my latest book's index on it.

In the process, I've noticed that the page numbers appear to be getting sorted lexically, not numerically. The following image is a screenshot showing this:

<img width="231" alt="Screen Shot 2020-05-03 at 1 43 30 PM" src="https://user-images.githubusercontent.com/311040/80922669-3eda2e00-8d44-11ea-88e7-53409d91cf47.png">

It's not a show stopper, but a nice-to-have.

**Comment by mojavelinux** [comment] 2020-05-03 21:38
It turns out this is a duplicate of a recent issue, which I just fixed. See #1657 (and the PR #1659).

**Closed by mojavelinux** 2020-05-03 21:38 UTC
