### ISSUE TITLE
Unwanted newline rendered in asciidoctor table cells 

### ISSUE THREAD

**Issue by david0** [asciidoctor/asciidoctor-pdf#1654] opened 2020-04-21 07:47 UTC
For asciidoc-formatted cells an additional (unwanted) newline is rendered.

E.g. for the following table:
```asciidoc
[cols="1,1"]
|===
|Header 1 |Header 2 

a|
Column 1, row 1

|


Column 2

|row 1

|Column 1, row 2
|Column 2, row 2
|===
```

asciidoctor-pdf 1.5.3 renders it as follows:
![asciidoctor-pdf 1.5.3 output](https://user-images.githubusercontent.com/1685610/79839279-91b2fd80-83b4-11ea-9d12-ad0f4b12bc43.png)

But the HTML output looks as follows:
![asciidoctor 2.0.10 html output with Firefox](https://user-images.githubusercontent.com/1685610/79839578-fd956600-83b4-11ea-8726-dd811401ef08.png)

I did not find a way to suppress that.

**Comment by mojavelinux** [comment] 2020-04-21 08:00
This is a duplicate of #1513. I'm going to try to solve it in the 2.0.0 release.

**Closed by mojavelinux** 2020-04-21 08:00 UTC

**Comment by david0** [comment] 2020-04-21 08:11
Sorry, did not see this duplicate. Good to hear that there will be improvements!

**Comment by mojavelinux** [comment] 2020-04-21 08:13
No worries. And I've linked the issues so your additional example is visible.
