### ISSUE TITLE
Admonition Background Colours/Borders

### ISSUE THREAD

**Issue by abradshaw** [asciidoctor/asciidoctor-pdf#342] opened 2015-10-27 20:30 UTC
Id like to request the ability to set the background colours and/or border settings of each admonition block please

**Comment by mojavelinux** [comment] 2017-03-08 05:12
#444 is a duplicate of this issue. Since it contains more context, I'm going to close this issue as a duplicate and let that one stand.

**Closed by mojavelinux** 2017-03-08 05:12 UTC
Labels: improvement
