### ISSUE TITLE
Setting page-background-image before a page break (<<<)?

### ISSUE THREAD

**Issue by rben01** [asciidoctor/asciidoctor-pdf#1882] opened 2021-02-27 19:16 UTC
I'm wondering if it's possible to choose a different `page-background-image` attribute for each page of a PDF. Similarly to how [`[.landscape]`](https://github.com/asciidoctor/asciidoctor-pdf/issues/490) can be applied before a page break, I'm wondering if it's possible to set `:page-background-image:` before a page break (or even anywhere in the document) so that either all subsequent pages use that background image, or so that all pages use that background image until the next manual page break (I'm not sure which behavior is preferable).

Something like this

    = Document Title
    :page-background-image: image:default_bg.png[]

    // This uses default_bg.png
    == Section 1
    Text

    :page-background-image: image:alt_bg.png[]
    <<<

    // This uses alt_bg.png
    == Section 2
    Text

**Comment by rben01** [comment] 2021-02-28 02:53
On second thought it might be best to add `background-image` as a general role attribute and then set the role on the page break, like so:

theme.yaml
```
role:
  alt-bg-img:
     background-image: image:alt_bg.png[]
```

text.adoc
```
[.alt-bg-img]
<<<
```

Of course, setting this role on something other than a page break should have no effect.

**Comment by mojavelinux** [comment] 2021-02-28 08:27
I consider this to be mostly a duplicate of #1739. I'd prefer to consolidate the issues. (Despite the fact that possible solutions have been proposed in that issue, this still remains a very difficult feature to implement due to how the converter / PDF generator works).

Although we're considering supporting roles in this converter, I don't think roles are appropriate for setting the background image of the page since it is too specific of a need.

**Closed by mojavelinux** 2021-02-28 08:27 UTC
