### ISSUE TITLE
Pages breaks inside example blocks result in example block not being rendered correctly

### ISSUE THREAD

**Issue by leluna** [asciidoctor/asciidoctor-pdf#885] opened 2018-02-20 14:48 UTC
If an example block is placed across pages, the frame extends to the end of the page and the rest of the example block on the next page does not have any frame. Normally, an example block would not be long enough for this case to happen. (In my case, the example includes several graphics so it easily spans more than one page.)

**Comment by free-easy** [comment] 2018-06-19 08:30
Facing the same problem.

![screenshot from 2018-06-19 10-25-36](https://user-images.githubusercontent.com/20483759/41585778-4bb84ca6-73ab-11e8-98f8-76d3e296c223.png)

**Comment by mojavelinux** [comment] 2019-09-01 05:42
This is a duplicate of #362 and was fixed in 1.5.0.beta.3.

**Closed by mojavelinux** 2019-09-01 05:42 UTC
Labels: duplicate
