### ISSUE TITLE
does asciidoctor-pdf support pdf/a format?

### ISSUE THREAD

**Issue by mariomuja** [asciidoctor/asciidoctor-pdf#1367] opened 2019-11-05 14:07 UTC
1.
Does asciidoctor-pdf support the PDF/A format for achiving purposes as described here?
https://en.wikipedia.org/wiki/PDF/A

2.
Is it possible to password protect a PDF created with asciidoctor-pdf?

Please excuse me if this is not the correct place for this type of question. 

Thanks for your help,
Mario

**Comment by mojavelinux** [comment] 2019-11-07 07:02
This is a duplicate of #125 and #911. Asciidoctor PDF is not a PDF library. We rely on the PDF library (Prawn) to support PDF formats / specs. So this has to happen upstream.

For password protection, you can use something like [hexapdf](https://hexapdf.gettalong.org/). Run the output of Asciidoctor PDF through that to add encryption or password protection.

**Closed by mojavelinux** 2019-11-07 07:02 UTC
Labels: duplicate

**Comment by mojavelinux** [comment] 2019-11-07 07:03
Prawn already embeds fonts and doesn't apply encryption. So the document is already portable. I'm not really sure what PDF/A adds that Prawn can't do. But, regardless, it's a Prawn issue.
