### ISSUE TITLE
Opacity in SVG images lost when generating PDF

### ISSUE THREAD

**Issue by djuran** [asciidoctor/asciidoctor-pdf#841] opened 2017-08-24 16:38 UTC
I've noticed that objects in an SVG which are partly transparent (e.g. opacity 50%), when added into an adoc and then run through asciidoctor-pdf, the resulting image in the PDF will be solid and not transparent at all. Please see the attached example
[test.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/1249606/test.zip)

**Comment by AlexanderZobkov** [comment] 2017-08-26 18:52
asciidoctor-pdf uses [prawn-svg](https://github.com/mogest/prawn-svg) under-the-hood to embed svg into pdf. According to the documentation and even test samples for prawn-svg, it appers it should suppport opacity property (the same as used in your test.svg file). I think it makes sense to double check with maintanter of prawn-svg by opening an issue.

**Comment by mojavelinux** [comment] 2019-04-08 12:01
Actually, the problem is that you're using two different opacity properties on the shape. The SVG declares the style for the top ellipse as follows:

```
style="opacity:0.75;fill:#ff6c52;fill-opacity:1;stroke:#000000;stroke-width:0.5"
```

As you can see, the fill-opacity is 1. If you change the fill-opacity to 0.75 (and drop opacity):

```
style="fill:#ff6c52;fill-opacity:0.75;stroke:#000000;stroke-width:0.5"
```

then you will find it works as expected.

It also works if you drop fill-opacity and just use opacity:

```
style="opacity:.75;fill:#ff6c52;stroke:#000000;stroke-width:0.5"
```

I've filed an issue upstream for prawn-svg to align with the behavior of SVG viewing programs (see https://github.com/mogest/prawn-svg/issues/109). Since there's a simple workaround, I'm closing this issue here.

**Closed by mojavelinux** 2019-04-08 12:01 UTC
