### ISSUE TITLE
{counter:attribute

### ISSUE THREAD

**Issue by jvprosser** [asciidoctor/asciidoctor-pdf#912] opened 2018-06-07 19:17 UTC
```
:!cn:
.Workload inventory
[cols=".^50,.^300,.^300",options="header",]
|===
3+^| *Workload Inventory*
 <a| {counter:cn})    |*row1*  |Answer here
 <a| {counter:cn})    |*row2*  |Answer here
 <a| {counter:cn})    |*row3*  |Answer here
 <a| {counter:cn})    |*row6*  |Answer here
|===
```

results in a pdf where the counter numbering in column 0 starts at 5
[testtable.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/2081809/testtable.pdf)

It seems to be the case that the number is initialized to be the next number in the sequence after the table. i.e. the numbering in the table able should be 1-4 but instead is 5-8. If I add another row, the numbering starts at 6.

**Comment by mojavelinux** [comment] 2018-10-27 07:58
The problem is that you are using an AsciiDoc table cell in the first column. That has side effects. It's not needed in this case, so dropping the style will solve your issue.

```
:!cn:
.Workload inventory
[cols=".^50,.^300,.^300",options="header",]
|===
3+^| *Workload Inventory*
 <| {counter:cn})    |*row1*  |Answer here
 <| {counter:cn})    |*row2*  |Answer here
 <| {counter:cn})    |*row3*  |Answer here
 <| {counter:cn})    |*row6*  |Answer here
|===
```

**Comment by mojavelinux** [comment] 2022-04-17 10:34
This problem has been addressed in Asciidoctor PDF 2. Therefore, I'm marking it as a duplicate with the label 2.0.0.

See #907 and #1986.

**Closed by mojavelinux** 2022-04-17 10:34 UTC
