### ISSUE TITLE
Nil can't be coerced into a float -- happens with stylesheet

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor-pdf#44] opened 2014-09-09 02:43 UTC
I get the error listed bellow when I use a style sheet with asciidoctor pdf. No pdf is generated.
Without the stylesheet, the pdf is generated without error.

```
$ asciidoctor-pdf -a pdf-style=base-theme.yml Poetry_8.ad 
/Users/carlson/.rvm/gems/ruby-2.1.1/gems/prawn-1.2.1/lib/prawn/document.rb:437:in `-': nil can't be coerced into Float (TypeError)
```

here is the style sheet:

```
base:
  font_size: 9
  line_height_length: 10

```

The error occurs with and without the trailing blank line.

**Comment by diniodinev** [comment] 2016-06-21 12:01
Is that implemented in the latest version? Partial configuration support?

**Comment by mojavelinux** [comment] 2016-06-21 17:45
Yes. Asciidoctor PDF now loads a base theme, so you should only have to specify what you need to configure. However, it is still strongly recommended that you provide custom fonts (or use the built-in names seen in https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml) or else you will run into character problems.

**Comment by mojavelinux** [comment] 2016-06-21 17:46
I'm going to mark this as a duplicate of #132, which is now resolved.

**Closed** 2016-06-21 17:46 UTC
Labels: duplicate
