### ISSUE TITLE
Generated images not found when srcdir != destdir

### ISSUE THREAD

**Issue by mbodmer** [asciidoctor/asciidoctor-pdf#271] opened 2015-07-15 14:30 UTC
I have defined `:imagesdir: assets` inside the document and have embedded some png graphics in my `$(SRCDIR)/assets` and also some asciidoctor-diagram generated graphics.

On the commandline i give the parameters: `-B $(SRCDIR) -D $(OUTDIR)`

The generated graphics can be found as expected in `$(OUTDIR)/assets.`

My problem now is asciidoctor-pdf does not find these generated graphics anymore since i have updated to the newest version (1.5.0.alpha.8). Before (version unknown) this was working, however.

The error message is as follows (real path exchanged with variables):
`asciidoctor: WARNING: image to embed not found or not readable: $(SRCDIR)/assets/generated_graphics.png`

I have also tried to generate html with embedded generated graphics in `asciidoctor`, this worked as expected. With these settings. I had to copy the static resources from `$(SRCDIR)/assets` to `$(OUTDIR)/assets`, however.

Is this a bug in asciidoctor-pdf, or do I have to do this differently?
I would like different src/dest directories.

**Comment by mojavelinux** [comment] 2015-07-17 08:11
I'll admit I haven't tested this scenario with Asciidoctor PDF yet. We're still working out resolving image paths since it's a surprisingly complex problem (because of the many scenarios). I'll be sure to check out this situation and report back with my findings.

**Comment by MaWiMa** [comment] 2015-07-17 13:23
this works for me on command line (apha8 and before):
asciidoctor-pdf  -a pdf-style=CCS -a pdf-stylesdir=CCS  -a imagesdir=../CCS/images somefile.txt
or in script
#!/usr/bin/ruby
require 'asciidoctor'
require 'asciidoctor-pdf'
...
some code
...
Asciidoctor.render_file f,
:base_dir => '.',
:to_dir => 'CCS/inclusion',
:backend => 'pdf',
:attributes => 'pdf-pages pdf-style=CCS pdf-stylesdir=CCS imagesdir=CCS/images includedir=included',
#:attributes => 'pdf-pages  imagesdir=CCS/images includedir=included',
:safe => 'safe'
...

(full script look at https://github.com/MaWiMa/CCS/blob/master/makePages.rb)

**Comment by hmolsen** [comment] 2015-12-22 09:52
Hi,
I use graphviz in asciidoctor-diagram with asciidoctorj-pdf from gradle and always use html5 and pdf as backends. I can confirm the issue and found the following (not beautiful, but working) workaround:

    //workaround for issue 271 https://github.com/asciidoctor/asciidoctor-pdf/issues/271
    :imagesdir-build: ../../../../build/asciidoc/{backend}/YOUR_DOC_FOLDER/images
    :imagesdir-src: images
    ifndef::imagesdir[:imagesdir: {imagesdir-src}]

so the default is the default images source directory, and when using a diagram:

    image:images.png[]
    
    :imagesdir: {imagesdir-build}
    [graphviz, diagram_title, png]
    ....
    YOUR_GRAPHVIZ_HERE
    ....
    :imagesdir: {imagesdir-src}
    
    image:images.png[]

now I can include images from the images source folder, and the generated images are read from the build folder. Specifying `{backend}` is necessary s.t. the html5 output relatively includes the images from its own folder. `{backend}` is replaced automatically by either `pdf`or `html5`, and it's used by asciidoctor to generate the build output directory name.

Note that you will have to adapt the images build dir path to wherever your generated images are dropped! This depends on your project structure.

**Comment by rockyallen** [comment] 2017-03-09 21:04
URLs don't seem to work either (alpha.14) even with allow-uri-read set.
Tried http:, https: and file:.

**Comment by mojavelinux** [comment] 2017-03-09 22:45
@rockyallen Can you test the following document:

image-from-uri.adoc
```
image::https://raw.githubusercontent.com/asciidoctor/asciidoctor/master/screenshot.png[]
```

Then run:

```
$ asciidoctor-pdf -a allow-uri-read image-from-uri.adoc
```

Also show the output from:

```
$ asciidoctor-pdf -v
```

**Comment by sbrannen** [comment] 2017-04-05 19:35
I just ran into the same problem when adding PDF support to the JUnit 5 build.

- Issue: https://github.com/junit-team/junit5/issues/770
- Commit: https://github.com/junit-team/junit5/commit/468158044c1b5e0e215d613504688e96aef5724a

We generate a diagram named `component-diagram.svg` using Plant UML.

This gets embedded in the generated HTML but not in the generated PDF.

Is there any chance to get an official fix for this?

Or do we need to implement a _work-around_ like @hmolsen suggested above?

**Comment by mojavelinux** [comment] 2017-04-05 20:49
@sbrannen As I mentioned above, this is definitely something that needs to be documented so we can all remember how to do it. But it is possible. There are three things that need to happen:

1. Set the imagesoutdir attribute so Asciidoctor Diagram generates files into the build directory (this may be the default now, I'd have to verify)
2. Copy the static images from the source location to the build directory prior to running Asciidoctor PDF

Once those two steps are done, all the images are aggregated in what I term the "images catalog" in the build output. When you run Asciidoctor PDF, set the imagesdir to the absolute directory of the images catalog (since Asciidoctor PDF is resolving "system" files). It then be able to find all images relative to the location of imagesdir.

As you can see, Asciidoctor PDF does need the help of a build system to aggregate the static images with the source images. It needs to see one, unified images catalog.

If you can verify that solution works, or provide revisions, then we'll document this setup in the README.

**Comment by sbrannen** [comment] 2017-04-05 20:52
@mojavelinux, Thanks for the reply!

That sounds quite doable. I don't have time to try it out at the moment, but I promise we'll give it a shot in the coming weeks for JUnit 5.

In fact, I'll link to your proposed solution from our ticket now.

Cheers,

Sam

**Comment by mojavelinux** [comment] 2017-04-05 20:53
Great!

**Comment by sbrannen** [comment] 2017-04-05 20:56
And.... this sounds much easier to resolve than the dreaded emoji work-around described in https://github.com/asciidoctor/asciidoctor-pdf/issues/323#issuecomment-143966293. 🤢 

JUnit Jupiter supports emoji in display names for tests, and I was rather disappointed to _not_ see them in the PDF version of our User guide. C'est la vie.

**Comment by sbrannen** [comment] 2017-04-06 22:42
OK, I can confirm that the proposed procedure from @mojavelinux works.

See https://github.com/junit-team/junit5/commit/cb8d49578740159871a4358707c01050d194e220 for details! 👍

**Comment by sbrannen** [comment] 2017-04-06 22:43
> If you can verify that solution works, or provide revisions, then we'll document this setup in the README.

I partially documented it in the build script and commit message for https://github.com/junit-team/junit5/commit/cb8d49578740159871a4358707c01050d194e220. 😉

**Comment by mojavelinux** [comment] 2017-04-07 00:34
See my follow-up here: https://github.com/junit-team/junit5/pull/779. It can actually be a lot simpler.

**Comment by mojavelinux** [comment] 2017-04-07 00:35
I think we've been able to prove that Asciidoctor Diagram and the latest build plugins now make it possible to handle this scenario. It is necessary to copy all images to the output directory. The only workaround for that is to resolve the image in multiple locations, which I'm going to file as a separate issue.

**Closed by mojavelinux** 2017-04-07 00:35 UTC
Labels: documentation

**Comment by andyjefferson** [comment] 2017-06-03 13:33
For reference, what is the issue number for "resolve the image in multiple locations"?

**Comment by mojavelinux** [comment] 2017-06-19 07:29
You reminded me to submit it. See https://github.com/asciidoctor/asciidoctor-pdf/issues/826.
