### ISSUE TITLE
Invalid breaks in words with accents in literal paragraphs

### ISSUE THREAD

**Issue by ogmios-voice** [asciidoctor/asciidoctor-pdf#979] opened 2018-12-11 07:23 UTC
Converting the following asciidoc document to pdf (using `asciidoctor-pdf-1.5.0.alpha.17.dev`)

```
:pdf-page-size: a5

= test

 aàbècìdòeùf gáhéiíjókúlým nâoêpîqôrûs tñuõvãw xäyëzïaöbücÿd
 aabbccddeef gghhiijjkkllm nnooppqqrrs ttuuvvw xxyyzzaabbccd
```

results in an **invalid break** in the first row. The resulting block of the pdf looks like this (for me):

```
aàbècìdòeùf gáhéiíjókúlým nâoêpîqôrûs tñuõvãw xäyëzïa
öbüc d
aabbccddeef gghhiijjkkllm nnooppqqrrs ttuuvvw
xxyyzzaabbccd
```

Note: the `ÿ` character is invisible in the result, but it is present if I copy the text from the pdf. (The invalid line break is real however.)

I assume this will be a **font** issue, as it is not present in the html generated with asciidoctor (regardless of the size of the window).

**Comment by mojavelinux** [comment] 2018-12-31 10:21
There are two things going on here.

First, the default font is missing the `ÿ` character (for some reason). We could address that by updating the font.

The second issue is by design. Asciidoctor PDF hardbreaks text in a verbatim block (such as a literal paragraph) at any character (since PDF can't scroll). The reason is that we assume that verbatim blocks are most likely some sort of source code and wrapping any other way doesn't make sense. I don't recall all the details, but there's a good reason for it.

**Comment by ogmios-voice** [comment] 2018-12-31 12:17
But the breaks should be consistent, and right now they are not: the current position of the break depends on whether a given letter is accented or not (this is what I was meaning by _invalid breaks_). So as of the initial example the correct result should be this:

```
aàbècìdòeùf gáhéiíjókúlým nâoêpîqôrûs tñuõvãw
xäyëzïaöbücÿd
aabbccddeef gghhiijjkkllm nnooppqqrrs ttuuvvw
xxyyzzaabbccd
```

**Comment by mojavelinux** [comment] 2022-05-03 10:14
I'm not sure when, but this problem seems to have been fixed in Prawn. I've added a test for it just to be sure.

**Closed by mojavelinux** 2022-05-03 10:14 UTC
Labels: bug, upstream
