### ISSUE TITLE
Is this highlight issue?

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#1272] opened 2019-09-12 12:53 UTC
version: current master commit bc9f454515d74ee3330beab8b2414ef065b1065f

Example document:

```
= test

== test highlight

regular #highlight of# text

As a result of hard `rule #1`, `rule #2` and `rule #3`, rows `##1,2,4,5,7,8,9,11` should be matched....

As a result of hard rule #1, `rule #2` and `rule #3`, rows `##1,2,4,5,7,8,9,11` should be matched....

```

PDF result:

![image](https://user-images.githubusercontent.com/234774/64785303-b7ea0280-d574-11e9-8a4f-bbc1b2aa19c5.png)

HTML result:

![image](https://user-images.githubusercontent.com/234774/64785331-ca643c00-d574-11e9-8a0e-06a70a1d27d2.png)

For me it looks like a kind of bug -- on both backends it is highlighted differently and incorrect.

I was expecting only the first row to be highlighted. But I am not sure if it was designed to work this way.

What do you think?

**Comment by mojavelinux** [comment] 2020-01-19 09:56
Here's the pseudo-HTML the parser is seeing:

```
rule <mark>1, <code>rule #2</code> and <code>rule #3</code>, rows <code></mark>#1,2,4,5,7,8,9,11</code> should be matched
```

Notice that the closing mark tag appears inside the opening code tag. The AsciiDoc has produced invalid HTML. How the two converters interpret this is different because the HTML parser in the browser is **way** more lenient and almost impossible to reproduce. So what Asciidoctor PDF is doing is technically more correct. It's closing the mark tag at the end of the last code tag instead of the beginning.

The correct fix is to fix the AsciiDoc so that you don't end up with invalid HTML. And that would be:

```
rule #1, `+rule #2+` and `+rule #3+`, rows `+##1,2,4,5,7,8,9,11+` should be matched
```

**Closed by mojavelinux** 2020-01-19 09:56 UTC
