### ISSUE TITLE
Images cannot float

### ISSUE THREAD

**Issue by antoyo** [asciidoctor/asciidoctor-pdf#353] opened 2015-11-06 04:46 UTC
Hello.
We can have floating image in the HTML5 backend using this syntax:

``` asciidoc
image::image.jpg[role="right"]
```

but it does not work in the PDF backend.

Thanks to fix this issue.

**Comment by mojavelinux** [comment] 2015-11-06 04:53
Floating images in PDF is extremely difficult, which is why we haven't done it yet. I do have a prototype of some text around images that can be found in editions (https://github.com/opendevise/editions/blob/master/lib/editions/pdf_extensions.rb#L88-L139). We're still considering how to integrate that into Asciidoctor PDF.

**Comment by antoyo** [comment] 2015-11-06 04:57
As an alternative, I tried using a table, but there is a lot of empty space at the bottom of the table.

Here is my code:

```asciidoc
[cols="2*"]
|===
|Some +
text

|image:image.jpg[]
|===
```

Is it normal that there is a big white space at the bottom of the table?

It seems to happen only when using an image inside a table.

Thanks for your help.

**Comment by mojavelinux** [comment] 2015-11-06 05:20
> It seems to happen only when using an image inside a table.

That definitely sounds like a bug. Images can throw off the cursor if not handled correctly, which could be happening in this case. I'll definitely look into it.

**Comment by mojavelinux** [comment] 2015-11-07 06:35
I think the problem is that inline images aren't properly expanding the cell height, which is the reason for #295 as well.

**Comment by atomfrede** [comment] 2015-12-04 07:58
@mojavelinux Is there any possibility I can try your pdf extension with ascidoctor pdf, as our documentation departement would like to have floating images in pdf too.

**Comment by mojavelinux** [comment] 2015-12-06 20:50
@atomfrede Yes, by all means.

**Comment by cocowalla** [comment] 2016-04-26 10:51
@atomfrede did you figure out how to try @mojavelinux PDF extension with Asciidoctor PDF? I'd also like to get floating images working

**Comment by atomfrede** [comment] 2016-04-26 10:56
@cocowalla No I didn't had time. We made some changes to the documents, such that floating images are not required anymore at the moment.

**Comment by wingfire** [comment] 2016-06-09 13:11
In the case "image in a table cell" i have the following effect with images wider than the cell:

1. Images with a small height are show twice
2. Higher images are shown once with a lot of white space below the image

**Comment by mojavelinux** [comment] 2016-06-11 07:13
As I've said many times before, what needs to be done to get AsciiDoc table cell content to work is to write a custom table cell implementation for Prawn that recurses back into the converter to handle arbitrary AsciiDoc content. Once that is done, in theory, we get support for all block-level AsciiDoc in a table cell for "free". Until then, trying to render AsciiDoc content in a table cell by cherry picking it is just a huge hack.

**Comment by sylock** [comment] 2017-04-01 12:26
So, what about a proper float implementation into PDF? Is it still in the pipe?

**Comment by bhagyas** [comment] 2018-09-27 08:28
Any updates on this issue?

**Comment by owjjh** [comment] 2018-10-10 12:37
+1

**Comment by oliviercailloux** [comment] 2019-09-15 13:06
>  I'll be posting about this new strategy on the list later this week.

Has this ever been done? A [search](https://discuss.asciidoctor.org/template/NamlServlet.jtp?macro=search_page&node=1&query=html+css+pdf&sort=date) did not reveal anything really relevant.

**Comment by mojavelinux** [comment] 2019-09-16 08:49
I've been waiting on the 1.5.0 release to push out the official announcement. I have been talking about it rather extensively in the gitter channel, though. The prototype can be found at https://github.com/mogztter/asciidoctor-pdf.js, but it's still early days.

**Comment by Thanatermesis** [comment] 2021-08-01 02:16
Same issue with epub3 renderings, I have no way to position images on the side with some text

Example code:

```
== Test section
.Title for image
image::einstein-relatividad.jpg[,340,role="related thumb left"]
Lorem Ipsum is simply dummy text of the printing a.....
```

----
So the HTML rendering (asciidoctor) renders very good, like:

# HTML:

![image](https://user-images.githubusercontent.com/1181626/127756927-5555d966-7266-4418-9740-71d42f52a88c.png)

----
But for PDF or for EPUB3, it always renders it in a strange and unfriendly way (I tried different options for the images, nothing found to work nicely yet):

----
# Epub:

![image](https://user-images.githubusercontent.com/1181626/127756941-c2913d33-38bf-4a66-8f04-ec5ca5f7a0bc.png)

----

# PDF:
![image](https://user-images.githubusercontent.com/1181626/127756950-1cc2405b-72f3-4c6d-8b51-2b7dd9c6d89e.png)

**Comment by mojavelinux** [comment] 2021-08-01 07:20
Please direct Asciidoctor EPUB3 feature requests to the issue tracker for that project. https://github.com/asciidoctor/asciidoctor-epub3/issues This issue tracker is only for issues that pertain to Asciidoctor PDF.

**Comment by mojavelinux** [comment] 2022-05-03 19:29
> It seems to happen only when using an image inside a table.

This issue was addressed by the fix for #1515. Here's how it looks now when using a table for layout.

![screenshot](https://user-images.githubusercontent.com/79351/166551538-d53ee87f-a038-43ab-ad50-0422349aac08.png)

It takes some fiddling to get the amount of text right per cell, but at least there is no extra bottom margin now.

**Closed** 2022-05-14 20:06 UTC
Labels: documentation

**Comment by mojavelinux** [comment] 2022-05-14 20:10
I'm thrilled to report that after all the changes and improvements that were made to the code for the 2.0.0 release, it became possible to implement this feature.

The way it works is that it will wrap successive paragraphs next to the floating image (an block image with the float attribute). The float box will be cleared once the content extends past the bottom of the image or another type of block is encountered. However, the code also adds a framework for enlisting additional block types in the float wrapping, which is explained in the documentation.

**Comment by mcoderz** [comment] 2023-11-13 18:27
@mojavelinux Is there a way to use [.float-group] with PDF? I'm traying put three image side by side, and I can do it in HTML, but not in PDF...

**Comment by mojavelinux** [comment] 2023-11-13 20:44
Please direct usage questions to the project chat at https://chat.asciidoctor.org. Thanks.
