### ISSUE TITLE
media=prepress fails to be processed by Kindle Publishing

### ISSUE THREAD

**Issue by mementum** [asciidoctor/asciidoctor-pdf#2477] opened 2024-01-15 10:53 UTC
`media` values of `screen` and `print` do upload and are processed with no problem.

`prepress` will be rejected. After adding an optimization pass with `rghost` (and obviously `ghostcript` in the background) it does then upload. I also tried the `Foxit PDF Editor`, applying only the `cleanup` optimization and it also did something which made the format good for Kindle Publishing.

Understanding that finding a very small thing in the PDF generation that could be slightly different could be a huge effort, I would propose that a small hint be added to the documentation, pointing that in case of any problem with the `prepress` media mode, an optimization pass can iron things out.

Best regards

**Comment by mojavelinux** [comment] 2024-01-15 21:27
This looks like a duplicate of #2476.

> I would propose that a small hint be added to the documentation, pointing that in case of any problem with the prepress media mode, an optimization pass can iron things out.

I'm open to accepting a pull request to add this information to the documentation.

**Comment by meonkeys** [comment] 2024-01-17 19:36
@mementum you can try this workaround I used to get a `prepress` PDF working with Lulu: https://github.com/meonkeys/print-this/blob/main/book/extensions.rb#L22

**Comment by mojavelinux** [comment] 2024-01-17 21:26
If we can confirm with local tools that this indeed fixes the validation error, we could consider adding this into the converter when media=prepress. But we have to be able to test it locally.

**Comment by meonkeys** [comment] 2024-01-18 01:12
`pdftotext` appears to be happy with the workaround, as discussed in [chat](https://asciidoctor.zulipchat.com/#narrow/stream/288690-users.2Fasciidoctor-pdf/topic/.E2.9C.94.20syntax.20error.20with.20prepress.20PDF.20on.20Lulu).

I'm using pdftotext version 22.02.0. Came to my workspace via poppler-utils 22.02.0-2ubuntu0.3 on Ubuntu 22.04.3 LTS 64-bit desktop.

**Closed** 2024-01-20 11:05 UTC
Labels: bug

**Comment by mementum** [comment] 2024-01-22 15:05
Thanks for the fix.

**Comment by mementum** [comment] 2024-01-23 20:37
Let me add positive feedback now that version `2.3.11` has been released: `media=prepress` is accepted by KDP.

**Comment by mojavelinux** [comment] 2024-01-23 21:55
Thanks for sharing @mementum! This makes me very happy. :man_dancing:
