### ISSUE TITLE
Corrupt page links in index

### ISSUE THREAD

**Issue by andswitch** [asciidoctor/asciidoctor-pdf#1902] opened 2021-03-30 11:02 UTC
If an index term is part of an anchor that is referred to by some cross references, and the term itself also appears in those references, then the page link in the index is not correct. For example,

```
.define ((foo))
[[def_foo]]
[source,python]
----
def foo(x):
  # ...
----
```

Then, having `xref:def_foo[]` somewhere corrupts the page link in the index when the reference automatically expands to the block title. On the other hand, `xref:def_foo[define foo]` does not corrupt the page link. You can also work around it by giving the block id a reftext i.e. `[[def_foo,define foo]]`.

In my case, the page number that ends up in the index seems to be the page that contains the last cross reference. When I click the page link, my PDF reader jumps to the page that contains the first cross reference.

P.S. I realize it's maybe a bit of a strange use case. :)

**Comment by mojavelinux** [comment] 2021-04-03 06:45
I'm unable to reproduce this problem. The page number I'm seeing in the index is correct, and when I click on it, it jumps to the block. Can you provide a test case that demonstrates it not working?

You are right, though, that this is fringe case. The AsciiDoc language is not clear about whether an index term is permitted in a block title that is used for automatic reftext. The safest, most standard approach is assign reftext to the block so that is used instead of the title.

**Comment by andswitch** [comment] 2021-04-03 20:20
In the test case below, it looks like the existence of the `Build` subsection header is responsible for corrupting the jump locations of the index links. They all jump to a reference rather than the block. If I remove that header, the jump locations are okay again.

Regardless of the `Build` subsection header, all 3 index entries get the page number 3.

I generated the pdf with `asciidoctor-pdf <file>`, using AsciiDoctor 2.0.12 and AsciiDoctor PDF 1.5.4.

```
= Test case

== Install

.((install.bash))
[[install_bash_1]]
[source,sh]
----
# <1>
----
<1> xref:build_sh_1[]

<<<

== Usage

=== Build

.((build.sh [1 of 2]))
[[build_sh_1]]
[source,sh]
----
# <1>
# <2>
----
<1> xref:install_bash_1[]
<2> xref:build_sh_2[]

<<<

.((build.sh [2 of 2]))
[[build_sh_2]]
[source,sh]
----
# <1>
# <2>
----
<1> xref:build_sh_1[]
<2> xref:install_bash_1[]

<<<

[index]
== Index
```

**Comment by mojavelinux** [comment] 2021-04-03 22:30
I'm happy to report that I was able to reproduce this with Asciidoctor PDF 1.5.4, but not with Asciidoctor PDF 2.0.0 (from the main branch). That means somehow or another, this was resolved in all the word that was done on Asciidoctor PDF 2.0.0.

I'll still add a test case for this in the suite to be sure the page numbers end up being correct. But it looks like no additional code change is required for Asciidoctor PDF 2.0.0.

**Comment by mojavelinux** [comment] 2021-04-03 22:53
I added the test case. If you can demonstrate there is still a problem using Asciidoctor PDF 2.0.0 (see https://github.com/asciidoctor/asciidoctor-pdf/blob/main/CONTRIBUTING-CODE.adoc#development), we can reopen and expand the test case.

**Closed by mojavelinux** 2021-04-03 22:53 UTC
Labels: infrastructure
