### ISSUE TITLE
Support on icons image mode

### ISSUE THREAD

**Issue by pdorrestijn** [asciidoctor/asciidoctor-pdf#1935] opened 2021-06-03 14:48 UTC
According to the asciidoc documentation it should be able to include inline icons using image mode (not referring to admonitions).
https://docs.asciidoctor.org/asciidoc/latest/macros/icon-macro/
```
:icons: image 
:icontype: svg
icon:local-icon-file[] Bla bla
```

I've set the iconsdir as an attribute via the plugin, however it doesn't seem to work (with or without predefined type) using:
    id 'org.asciidoctor.jvm.gems' version '3.3.2'
    id 'org.asciidoctor.jvm.convert' version '3.3.2'
    id 'org.asciidoctor.jvm.pdf' version '3.3.2'
All I get is a parsed (and substituted) text: local icon file

I was able to get this to work with admonitions like this:
```
[NOTE,icon=local-icon-file.svg]
====
Bla bla
====
```
So all attributes were correctly setup, but I like to use it without admonitions like the asciidoc documentation prescribes the icon image mode.
Is this maybe not supported or broken in the plugin version 3.3.2?

**Comment by mojavelinux** [comment] 2021-06-03 18:48
This converter does not currently support image-based admonition icons defined globally. That's a duplicate of #1770. It is possible to specify an image per block, as you have correctly pointed out.

**Closed by mojavelinux** 2021-06-03 18:48 UTC
