### ISSUE TITLE
after-toc page numbering when using prepress mode

### ISSUE THREAD

**Issue by mateibarbu19** [asciidoctor/asciidoctor-pdf#2398] opened 2023-02-28 18:08 UTC
Hello,

I noticed that when enabling prepress mode, the first chapters page is 2, instead of 1.

Is this a bug, or am I doing something wrong? I tried to follow the source [code](https://github.com/asciidoctor/asciidoctor-pdf/blob/03e8ebbecc52d8a067489e23816f8e8bcd8758dc/lib/asciidoctor/pdf/converter.rb#L2374), but failed due to lack of knowledge.

My source file, `source.adoc`:
```
:doctype: book
:reproducible:
:toc: macro
:media: prepress
:pdf-theme: theme.yml

= Interesting Title

[abstract]
.Abstract

Documentation is a distillation of many long adventures.

toc::[]

== The only Chapter

Dear reader, hello!
```

My theme file, `theme.yaml`:
```yaml
extends: default-for-print
page:
  numbering:
    start-at: after-toc
```

Run:
```sh
asciidoctor-pdf source.adoc
```

**Comment by mojavelinux** [comment] 2023-03-26 10:00
As to to whether this behavior is by design, the answer is yes. But can we change the behavior so that `after-toc` refers to the first recto page after the toc? I think the answer is also yes. I've submitted a PR with the proposed change.

**Comment by mojavelinux** [comment] 2023-03-26 10:39
This change will require a documentation update.

**Comment by mateibarbu19** [comment] 2023-03-26 20:06
Thanks for your help! I will close the issue since any discussions on this matter can follow on the PR.

**Comment by mojavelinux** [comment] 2023-03-26 21:32
Actually, the PR will close the issue, so I prefer to keep it open until then. But I should be merging it shortly.

**Comment by mojavelinux** [comment] 2023-03-29 08:59
I think it's safe to reclassify this as a bug. The converter already skips the verso page after a chapter, and the toc in a book acts as a chapter. It seems unlikely someone would want to start content on the verso page. So we can think of "after-toc" in a prepress book to mean the first recto page after the last page of the toc.

**Closed** 2023-03-29 10:33 UTC
Labels: bug, documentation
