### ISSUE TITLE
Add built-in attribute for code highlighting and formatting that sets presubs/subs values.

### ISSUE THREAD

**Issue by smru** [asciidoctor/asciidoctor-pdf#760] opened 2017-02-24 09:42 UTC
```
[subs="verbatim,attributes,macros"]
-----------------------------------
$ <command>
$ rm -rf / pass:q[<span style="color: OrangeRed;">(Don't try!)</span>]
-----------------------------------
```

Request: At the moment I have to add the **[subs="verbatim,attributes,macros"]** line for every code block in my document. A global attribute for settings **subs** similar to **prewrap** would make the source code of the document much cleaner.

**Comment by mojavelinux** [comment] 2017-02-24 10:10
This is a duplicate of https://github.com/asciidoctor/asciidoctor/issues/2021.

This has to be handled in core, not in Asciidoctor PDF, so I'll close this issue since we have one that covers the request in core.

**Closed by mojavelinux** 2017-02-24 10:10 UTC
