### ISSUE TITLE
RTL and unicode is not supported

### ISSUE THREAD

**Issue by omidp** [asciidoctor/asciidoctor-pdf#400] opened 2016-02-11 07:55 UTC
I created a simple file to test asciidoctor pdf and it does not show unicode character in pdf. 
I get this error : 

`[omidp@omidpc ascidoc_test]$ asciidoctor-pdf test.adoc 
/home/omidp/.gem/ruby/gems/pdf-core-0.6.0/lib/pdf/core/pdf_object.rb:61: warning: regexp match /.../n against to UTF-8 string
`
[test.adoc](https://gist.github.com/omidp/f2778b342931a50f4a23)

I'm using asciidoctor 1.5.4.

**Comment by mojavelinux** [comment] 2016-02-11 12:00
I'm pretty sure this is related to (likely a duplicate of) the following issue: #308.

**Comment by mojavelinux** [comment] 2016-08-08 05:36
pdf-core 0.6.1 removed the `n` flag from the regexp, so literal strings outside the ASCII range are now converted properly.

**Comment by mojavelinux** [comment] 2016-08-08 06:27
I believe this is now resolved as part of the fix for #308. If you are still encountering a separate problem, please file a separate issue and provide a sample document for testing.

**Closed by mojavelinux** 2016-08-08 06:27 UTC
Labels: compliance
