### ISSUE TITLE
How to change font in stem equations

### ISSUE THREAD

**Issue by angelog0** [asciidoctor/asciidoctor-pdf#1674] opened 2020-05-01 14:58 UTC
I wrote a document that uses `stem` equations and that I compile both with `ascidoctor` (to produce an HTML file) and `asciidoctor-pdf` (to produce a PDF file). With `asciidoctor-pdf` I use the extension `asciidoctor-mathematical` and `mathematical-format=svg`. 

Now in PDF output the font used for the equations is very poor. I am following [this](https://asciidoctor.org/docs/asciidoctor-pdf) document. There is a [section](https://asciidoctor.org/docs/asciidoctor-pdf/#fonts-in-svg-images) about the font in SVG images but I  do not understand how to change the font for `stem` equations: it reports the example for font in diagram not in `stem` equations. 

In the following archive there are two example, one from an HTM file and one from a PDF file, to proof tha bad quality font in PDF.

[font_demo.tar.gz](https://github.com/asciidoctor/asciidoctor-pdf/files/4564786/font_demo.tar.gz)

I would be grateful if you can suggest also a good font for that.

TIA,
  Angelo.

**Comment by mojavelinux** [comment] 2020-05-02 07:12
This has nothing to do with fonts. Asciidoctor Mathematical converts equations into SVG paths using mathematical (which uses the Math fonts at a low level, but what it makes are paths). Asciidoctor PDF then converts these paths into PDF objects using Prawn.

Right now, the height of the image cannot be controlled. It is preset by Asciidoctor Mathematical (based on a zoom level of 1). I always get a height 17px (which works out to 12.75pt) for a single line and 27px for two lines, etc

```
image:stem-44ecc32004b3425be206425da57c70cc.svg[width=114,height=17]
```

This one size fits causes problems if the base font size of your document doesn't match. Asciidoctor Mathematical needs to provide a way to customize the size, so please file an issue there.

As far as Asciidoctor PDF is concerned, this is a duplicate of this issue: https://github.com/asciidoctor/asciidoctor-pdf/issues/1483#issuecomment-573061077. The decision as to which size to use is made in Asciidoctor Mathematical, though as the issue suggests, we may provide hints back and forth to get it to fit better in the line.

**Closed by mojavelinux** 2020-05-02 07:12 UTC

**Comment by angelog0** [comment] 2020-05-02 12:58
Thanks. I wrote [#80](https://github.com/asciidoctor/asciidoctor-mathematical/issues/80#issue-611182957)
