### ISSUE TITLE
Borders for section headers

### ISSUE THREAD

**Issue by MonaElsa** [asciidoctor/asciidoctor-pdf#1008] opened 2019-02-27 08:53 UTC
Hello,
I'm designing a PDF document with Asciidoctor. I need a possibility to set borders for section headers (see below). Is there currently a possibility?

<img width="791" alt="bildschirmfoto 2019-02-27 um 09 50 44" src="https://user-images.githubusercontent.com/47977208/53477581-497ca180-3a75-11e9-97a6-56eca61a69df.png">

**Comment by mojavelinux** [comment] 2019-02-27 11:39
This is a duplicate of #434. Please continue the discussion there.

**Closed by mojavelinux** 2019-02-27 11:39 UTC
