### ISSUE TITLE
previous section title appears in the header of the next part page

### ISSUE THREAD

**Issue by kuboaki** [asciidoctor/asciidoctor-pdf#879] opened 2018-01-04 10:41 UTC
The case of 'book' type asciidoc file which uses 'section-or-chapter-title',  last chapter name of the previous part appears in the header of the next part's title page.
![180104-0015](https://user-images.githubusercontent.com/78203/34559923-314469fa-f187-11e7-9622-882f162d40e2.png)

**Comment by mojavelinux** [comment] 2018-11-24 15:09
Duplicate of #910. Resolved by e2713187023fb46f246b92c57cdd9b2835b5faf9.

**Closed by mojavelinux** 2018-11-24 15:09 UTC

**Comment by kuboaki** [comment] 2018-11-28 04:50
@mojavelinux Thanks!
