### ISSUE TITLE
Support for PDF/X-1a

### ISSUE THREAD

**Issue by gdamore** [asciidoctor/asciidoctor-pdf#911] opened 2018-05-28 05:34 UTC
(I won't be surprised if the answer here is "not going to do it", but I think it may be helpful to file this.)

I'm using asciidoctor to produce book content for submission to press printers.  I've been advised that the printer would prefer to have content in PDF/X format, as this seems to guarantee that certain print results will always be reducible.  Given the rather poor results (font issues) I had with another document produced by asciidoctor with the same printer, I'm thinking it would be good if we had a way to generate PDF/X compliant documents.

I know it is possible to use Adobe Acrobat Pro to convert PDF to PDF/X.  It would be nice not to have to spend hundreds of dollars for this though. 

I think PDF/X-1a is sufficient for most pre-press needs.

There may be similar desires for PDF/A.

**Comment by mojavelinux** [comment] 2018-05-28 07:10
I'm not against supporting this, and I recognize there is a need for it. However, it's just not something we can control from Asciidoctor PDF (as far as I understand). It needs to be implemented first in Prawn. Asciidoctor PDF will then be able to take advantage of that support. And there's actually an open pull request to add it in Prawn. See https://github.com/prawnpdf/prawn/pull/1029

**Comment by gdamore** [comment] 2018-05-28 15:01
Well that is good news. :)

**Comment by mojavelinux** [comment] 2020-03-20 06:25
This is a duplicate of #125. I'm closing this issue so we can keep the conversation consolidated.

**Closed by mojavelinux** 2020-03-20 06:25 UTC
Labels: upstream
