### ISSUE TITLE
[horizontal] block

### ISSUE THREAD

**Issue by ssydorov** [asciidoctor/asciidoctor-pdf#857] opened 2017-10-15 13:42 UTC
Hi to all!
could you help me with nex issue:

source file look like:

```asciidoc
.PC specification
[horizontal]
CPU:: i7-8700
GPU:: GeForce 1080
RAM:: 32 GB
```

HTML result looks fine:
![image](https://user-images.githubusercontent.com/24498236/31585259-9795287a-b1c7-11e7-88c0-a520369fe2bf.png)

but pdf version looks not so fine:

![image](https://user-images.githubusercontent.com/24498236/31585274-b14366e2-b1c7-11e7-9a3b-953d6a451de8.png)

this issue was tested on Windows 10
last version of asciidoctor and asciidoctor-pdf.

Thanks,
regards,
Sergiy.

**Comment by veeg** [comment] 2017-10-15 14:06
Duplicate of #310

**Closed** 2019-09-18 10:35 UTC
Labels: duplicate
