### ISSUE TITLE
Test failures in the Guix build container

### ISSUE THREAD

**Issue by Apteryks** [asciidoctor/asciidoctor-pdf#1725] opened 2020-07-15 02:02 UTC
Hello,

This is not a bug per see, as the test suite currently passes on the master branch when using a bundle environment, but rather a report of my findings when attempting to build this with slightly more up-to-date dependencies.

Ruby is at version 2.6.5, and the GEM_PATH entire dependencies in the build container are:

```
/gnu/store/8ql9jjzl8q291ghsxlkm1wn5bpdvgcqw-ruby-2.6.5/lib/ruby/vendor_ruby
/gnu/store/5sryx0ww0hm38s3qg6hybfkq3mg24ldg-ruby-chunky-png-1.3.11-1.143b9cd/lib/ruby/vendor_ruby
/gnu/store/14c4yw3jz0d4w5jyvx07drlr9xcrjh32-ruby-coderay-1.1.2/lib/ruby/vendor_ruby
/gnu/store/ap990sshhvfjy8x40n9rkk3v7vmxi7is-ruby-pdf-inspector-1.3.0-1.00ee4c9/lib/ruby/vendor_ruby
/gnu/store/d3416bvywc07prm88h67bk56azghi96c-ruby-rouge-3.21.0/lib/ruby/vendor_ruby
/gnu/store/0hlivkh2fhr6198drvz6fv0cyifa8js2-ruby-rspec-3.8.0/lib/ruby/vendor_ruby
/gnu/store/4jj3kvmakig63s0hcv2214kf3lr2xng2-ruby-asciidoctor-2.0.10/lib/ruby/vendor_ruby
/gnu/store/8z5nv7awf3yiycvhghkiqi02k5f6yzqm-ruby-concurrent-1.1.5/lib/ruby/vendor_ruby
/gnu/store/zylq4s2ms9ds0zvb4xqrpd9w6a74sp5w-ruby-open-uri-cached-0.0.5/lib/ruby/vendor_ruby
/gnu/store/m4plsrzfzz3lzvc9nmihkfm0cirralqn-ruby-prawn-2.2.2-1.d980247/lib/ruby/vendor_ruby
/gnu/store/afr7djqaa220g8a0bzy2i7739zg485z7-ruby-prawn-icon-2.5.0/lib/ruby/vendor_ruby
/gnu/store/fsvs51542da1nsdkii1011v7z7a74bpl-ruby-prawn-svg-0.30.0/lib/ruby/vendor_ruby
/gnu/store/jphxl4c5ry5pp7hnlxjc4a34g7j9msx5-ruby-prawn-table-0.2.2/lib/ruby/vendor_ruby
/gnu/store/xrx2z7d3s76a877qi75nxq7f86vmg25y-ruby-prawn-templates-0.1.2/lib/ruby/vendor_ruby
/gnu/store/xkg30bsiljbcfc7msrmj4zvhfaqh5npx-ruby-safe-yaml-1.0.5/lib/ruby/vendor_ruby
/gnu/store/f5ns66dw0mzcnihlj9sa31d1j524nzj9-ruby-text-hyphen-1.4.1/lib/ruby/vendor_ruby
/gnu/store/21im6y79mvyz3ala8v5yzwbfsnxh0swp-ruby-thread-safe-0.3.6/lib/ruby/vendor_ruby
/gnu/store/69mbvhajqaqa22m911vbcqk4qjqfq113-ruby-treetop-1.6.10/lib/ruby/vendor_ruby
/gnu/store/z8qlzzccwcv6n61a6ni8npc6djxwqz8m-ruby-ttfunk-1.6.2.1/lib/ruby/vendor_ruby
/gnu/store/hr3a68fhk29mr97nsb6k2053kcz68kvp-ruby-pdf-reader-2.4.0/lib/ruby/vendor_ruby
/gnu/store/2m96b69lwiqnj5l989v8qawxzlbjgv4a-ruby-rspec-expectations-3.8.2/lib/ruby/vendor_ruby
/gnu/store/zlyg13d32zc5zlh9ml92xgalakfmli3s-ruby-rspec-mocks-3.8.0/lib/ruby/vendor_ruby
/gnu/store/sxgvkvs1j9n2cbm5p3ixbvv6gb120j6b-ruby-rspec-core-3.8.0/lib/ruby/vendor_ruby
/gnu/store/qfalg2jgwlzw2l9kx51hl67r0mcczawh-ruby-pdf-core-0.8.1/lib/ruby/vendor_ruby
/gnu/store/pf97gc3hsq6ly8i0729r3jl25yqc19w7-ruby-css-parser-1.7.1/lib/ruby/vendor_ruby
/gnu/store/xa9biw1aydrkr09y4hr8q5isbqg64ifm-ruby-polyglot-0.3.5/lib/ruby/vendor_ruby
/gnu/store/svhb091bg26xmnl9vmy2hwchrr9xqdpy-ruby-rc4-0.1.5/lib/ruby/vendor_ruby
/gnu/store/bsjihw783xapk0biji4kd0r4fg6x44s7-ruby-hashery-2.1.2/lib/ruby/vendor_ruby
/gnu/store/pk7v6vv1cp5ydafnqlryw6f5cs97d0fz-ruby-ascii85-1.0.3/lib/ruby/vendor_ruby
/gnu/store/wd813n4s82f4a9cxigjr88sm7szbynkc-ruby-afm-0.2.2/lib/ruby/vendor_ruby
/gnu/store/bh3mf0yg7y62p5r84f7n2q28cm4a86ma-ruby-diff-lcs-1.3/lib/ruby/vendor_ruby
/gnu/store/wq9l3yhxnhryvx6yrbzqz573dv6d3828-ruby-rspec-support-3.8.0/lib/ruby/vendor_ruby
/gnu/store/hgmqh41xc6gywqvr9iid28phvixg47mc-ruby-addressable-2.7.0/lib/ruby/vendor_ruby
/gnu/store/z5584maa9995lyg0x4aqnql27hyf1h7i-ruby-public-suffix-4.0.1/lib/ruby/vendor_ruby
```

Noteworthy is the prawn version used (latest master branch), which pulls in pdf-core (0.8.1 instead of 0.7.0) and ttfunk (1.6.2.1 instead of 1.5.1). With these changes, I get 23 test failures:

```
starting phase `check'
.....................................FF......................................F..F...............................................F....................................................F.......................................................................FFFFFF...asciidoctor: WARNING: problem encountered in image: /tmp/guix-build-ruby-asciidoctor-pdf-1.5.3.drv-0/source/spec/fixtures/svg-with-remote-image.svg; Error retrieving URL https://cdn.jsdelivr.net/gh/asciidoctor/asciidoctor-pdf@v1.5.0.rc.2/spec/fixtures/logo.png: Failed to open TCP connection to cdn.jsdelivr.net:443 (getaddrinfo: Name or service not known)
........FF...............asciidoctor: WARNING: could not retrieve remote image: https://cdn.jsdelivr.net/gh/asciidoctor/asciidoctor-pdf@v1.5.0.rc.2/spec/fixtures/logo.png; Failed to open TCP connection to cdn.jsdelivr.net:443 (getaddrinfo: Name or service not known)
F...........................................................................................................................................................................FFFF...........................................................................................................................................................................................................................................................................................................................F............................................................................................................................................................................................asciidoctor: WARNING: could not retrieve remote image: https://img.youtube.com/vi/EJ09pSuA9hw/maxresdefault.jpg; Failed to open TCP connection to img.youtube.com:443 (getaddrinfo: Name or service not known)
.F.....................

Failures:

  1) asciidoctor-pdf Require should load converter if backend is pdf and require is asciidoctor-pdf
     Failure/Error: (expect res.exitstatus).to be 0

       expected #<Integer:1> => 0
            got #<Integer:3> => 1

       Compared using equal?, which compares object identity,
       but expected and actual are not the same object. Use
       `expect(actual).to eq(expected)` if you don't care about
       object identity in this example.
     # ./spec/cli_spec.rb:25:in `block (3 levels) in <top (required)>'

  2) asciidoctor-pdf Require should load converter if backend is pdf and require is asciidoctor/pdf
     Failure/Error: (expect res.exitstatus).to be 0

       expected #<Integer:1> => 0
            got #<Integer:3> => 1

       Compared using equal?, which compares object identity,
       but expected and actual are not the same object. Use
       `expect(actual).to eq(expected)` if you don't care about
       object identity in this example.
     # ./spec/cli_spec.rb:33:in `block (3 levels) in <top (required)>'

  3) Asciidoctor::PDF::Converter - Cover Page should scale front cover image with aspect ratio taller than page until it covers page if fit=cover
     Failure/Error: (expect cover_image[:width]).to eql pdf_page_size[0]

       expected: 612
            got: 612.0

       (compared using eql?)
     # ./spec/cover_page_spec.rb:180:in `block (2 levels) in <top (required)>'

  4) Asciidoctor::PDF::Converter - Cover Page should not allow page size of PDF cover page to affect page size of document
     Failure/Error: (expect pdf.pages[0][:size]).to eql PDF::Core::PageGeometry::SIZES['LETTER']

       expected: [612.0, 792.0]
            got: [612, 792]

       (compared using eql?)
     # ./spec/cover_page_spec.rb:229:in `block (2 levels) in <top (required)>'

  5) Asciidoctor::PDF::Converter - Font font sizes should resolve font size of inline element specified in rem
     Failure/Error: (expect linked_text[:font_size]).to eql 9.0

       expected: 9.0
            got: 9

       (compared using eql?)
     # ./spec/font_spec.rb:330:in `block (3 levels) in <top (required)>'

  6) Asciidoctor::PDF::FormattedText::Formatter Roles should allow custom role to specify relative font size
     Failure/Error: (expect min_text[:font_size]).to eql 18.0

       expected: 18.0
            got: 18

       (compared using eql?)
     # ./spec/formatted_text_formatter_spec.rb:508:in `block (3 levels) in <top (required)>'

  7) Asciidoctor::PDF::Converter - Image SVG should display text inside link
     Failure/Error: (expect text[0][:font_size]).to eql 12.0

       expected: 12.0
            got: 12

       (compared using eql?)
     # ./spec/image_spec.rb:255:in `block (3 levels) in <top (required)>'

  8) Asciidoctor::PDF::Converter - Image SVG should map font names in SVG to font names in document font catalog
     Failure/Error: (expect text[0][:font_size]).to eql 12.0

       expected: 12.0
            got: 12

       (compared using eql?)
     # ./spec/image_spec.rb:267:in `block (3 levels) in <top (required)>'

  9) Asciidoctor::PDF::Converter - Image SVG should replace unrecognized font family with base font family
     Failure/Error: (expect text[0][:font_size]).to eql 12.0

       expected: 12.0
            got: 12

       (compared using eql?)
     # ./spec/image_spec.rb:279:in `block (3 levels) in <top (required)>'

  10) Asciidoctor::PDF::Converter - Image SVG should map generic font family to AFM font by default
      Failure/Error: (expect text[0][:font_size]).to eql 12.0

        expected: 12.0
             got: 12

        (compared using eql?)
      # ./spec/image_spec.rb:291:in `block (3 levels) in <top (required)>'

  11) Asciidoctor::PDF::Converter - Image SVG should allow generic font family to be mapped in font catalog
      Failure/Error: (expect text[0][:font_size]).to eql 12.0

        expected: 12.0
             got: 12

        (compared using eql?)
      # ./spec/image_spec.rb:305:in `block (3 levels) in <top (required)>'

  12) Asciidoctor::PDF::Converter - Image SVG should replace unrecognized font family in SVG with SVG fallback font family if specified in theme
      Failure/Error: (expect text[0][:font_size]).to eql 12.0

        expected: 12.0
             got: 12

        (compared using eql?)
      # ./spec/image_spec.rb:320:in `block (4 levels) in <top (required)>'
      # ./spec/image_spec.rb:310:in `each'
      # ./spec/image_spec.rb:310:in `block (3 levels) in <top (required)>'

  13) Asciidoctor::PDF::Converter - Image PDF should insert page at location of block macro if target is a PDF
      Failure/Error: (expect pages[1][:size]).to eql PDF::Core::PageGeometry::SIZES['LETTER']

        expected: [612.0, 792.0]
             got: [612, 792]

        (compared using eql?)
      # ./spec/image_spec.rb:462:in `block (3 levels) in <top (required)>'

  14) Asciidoctor::PDF::Converter - Image PDF should replace empty page at location of block macro if target is a PDF
      Failure/Error: (expect pages[1][:size]).to eql PDF::Core::PageGeometry::SIZES['LETTER']

        expected: [612.0, 792.0]
             got: [612, 792]

        (compared using eql?)
      # ./spec/image_spec.rb:487:in `block (3 levels) in <top (required)>'

  15) Asciidoctor::PDF::Converter - Image Remote should read remote image over HTTPS if allow-uri-read is set
      Failure/Error: (expect images).to have_size 1
        expected [] to have size 1, but was 0
      # ./spec/image_spec.rb:690:in `block (3 levels) in <top (required)>'

  16) Asciidoctor::PDF::Converter - Page Size should set page size specified by pdf-page-size attribute using predefined name
      Failure/Error: (expect pdf.pages[0][:size]).to eql PDF::Core::PageGeometry::SIZES['LETTER']

        expected: [612.0, 792.0]
             got: [612, 792]

        (compared using eql?)
      # ./spec/page_spec.rb:22:in `block (3 levels) in <top (required)>'

  17) Asciidoctor::PDF::Converter - Page Size should set page size specified by pdf-page-size attribute using dimension array in points
      Failure/Error: (expect pdf.pages[0][:size]).to eql [600.0, 800.0]

        expected: [600.0, 800.0]
             got: [600, 800]

        (compared using eql?)
      # ./spec/page_spec.rb:32:in `block (3 levels) in <top (required)>'

  18) Asciidoctor::PDF::Converter - Page Size should set page size specified by pdf-page-size attribute using dimension array in inches
      Failure/Error: (expect pdf.pages[0][:size]).to eql PDF::Core::PageGeometry::SIZES['LETTER']

        expected: [612.0, 792.0]
             got: [612, 792]

        (compared using eql?)
      # ./spec/page_spec.rb:42:in `block (3 levels) in <top (required)>'

  19) Asciidoctor::PDF::Converter - Page Size should set page size specified by pdf-page-size attribute using dimension string in inches
      Failure/Error: (expect pdf.pages[0][:size]).to eql PDF::Core::PageGeometry::SIZES['LETTER']

        expected: [612.0, 792.0]
             got: [612, 792]

        (compared using eql?)
      # ./spec/page_spec.rb:52:in `block (3 levels) in <top (required)>'

  20) Asciidoctor::PDF::Converter - Table Dimensions should not break words in head row when autowidth option is set
      Failure/Error: (expect pdf.find_text 'Operation').not_to be_empty
        expected `[].empty?` to return false, got true
      # ./spec/table_spec.rb:400:in `block (3 levels) in <top (required)>'

  21) Asciidoctor::PDF::Converter - Video Vimeo should replace video with poster image if allow-uri-read attribute is set
      Failure/Error:
        poster = ::OpenURI.open_uri %(http://vimeo.com/api/v2/video/#{video_id}.xml), 'r' do |f|
          /<thumbnail_large>(.*?)<\/thumbnail_large>/ =~ f.read && $1
        end

      SocketError:
        Failed to open TCP connection to vimeo.com:80 (getaddrinfo: Name or service not known)
      # ./lib/asciidoctor/pdf/converter.rb:1599:in `convert_video'
      # ./lib/asciidoctor/pdf/converter.rb:138:in `convert'
      # ./lib/asciidoctor/pdf/converter.rb:155:in `traverse'
      # ./lib/asciidoctor/pdf/converter.rb:267:in `block in convert_document'
      # ./lib/asciidoctor/pdf/converter.rb:596:in `indent_section'
      # ./lib/asciidoctor/pdf/converter.rb:214:in `convert_document'
      # ./lib/asciidoctor/pdf/converter.rb:138:in `convert'
      # ./spec/spec_helper.rb:418:in `to_pdf_file'
      # ./spec/video_spec.rb:36:in `block (3 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # SocketError:
      #   getaddrinfo: Name or service not known
      #   ./lib/asciidoctor/pdf/converter.rb:1599:in `convert_video'

Finished in 2 minutes 32.6 seconds (files took 1.83 seconds to load)
990 examples, 21 failures

Failed examples:

rspec ./spec/cli_spec.rb:23 # asciidoctor-pdf Require should load converter if backend is pdf and require is asciidoctor-pdf
rspec ./spec/cli_spec.rb:31 # asciidoctor-pdf Require should load converter if backend is pdf and require is asciidoctor/pdf
rspec ./spec/cover_page_spec.rb:165 # Asciidoctor::PDF::Converter - Cover Page should scale front cover image with aspect ratio taller than page until it covers page if fit=cover
rspec ./spec/cover_page_spec.rb:213 # Asciidoctor::PDF::Converter - Cover Page should not allow page size of PDF cover page to affect page size of document
rspec ./spec/font_spec.rb:323 # Asciidoctor::PDF::Converter - Font font sizes should resolve font size of inline element specified in rem
rspec ./spec/formatted_text_formatter_spec.rb:495 # Asciidoctor::PDF::FormattedText::Formatter Roles should allow custom role to specify relative font size
rspec ./spec/image_spec.rb:247 # Asciidoctor::PDF::Converter - Image SVG should display text inside link
rspec ./spec/image_spec.rb:259 # Asciidoctor::PDF::Converter - Image SVG should map font names in SVG to font names in document font catalog
rspec ./spec/image_spec.rb:271 # Asciidoctor::PDF::Converter - Image SVG should replace unrecognized font family with base font family
rspec ./spec/image_spec.rb:283 # Asciidoctor::PDF::Converter - Image SVG should map generic font family to AFM font by default
rspec ./spec/image_spec.rb:295 # Asciidoctor::PDF::Converter - Image SVG should allow generic font family to be mapped in font catalog
rspec ./spec/image_spec.rb:309 # Asciidoctor::PDF::Converter - Image SVG should replace unrecognized font family in SVG with SVG fallback font family if specified in theme
rspec ./spec/image_spec.rb:449 # Asciidoctor::PDF::Converter - Image PDF should insert page at location of block macro if target is a PDF
rspec ./spec/image_spec.rb:468 # Asciidoctor::PDF::Converter - Image PDF should replace empty page at location of block macro if target is a PDF
rspec ./spec/image_spec.rb:687 # Asciidoctor::PDF::Converter - Image Remote should read remote image over HTTPS if allow-uri-read is set
rspec ./spec/page_spec.rb:15 # Asciidoctor::PDF::Converter - Page Size should set page size specified by pdf-page-size attribute using predefined name
rspec ./spec/page_spec.rb:25 # Asciidoctor::PDF::Converter - Page Size should set page size specified by pdf-page-size attribute using dimension array in points
rspec ./spec/page_spec.rb:35 # Asciidoctor::PDF::Converter - Page Size should set page size specified by pdf-page-size attribute using dimension array in inches
rspec ./spec/page_spec.rb:45 # Asciidoctor::PDF::Converter - Page Size should set page size specified by pdf-page-size attribute using dimension string in inches
rspec ./spec/table_spec.rb:380 # Asciidoctor::PDF::Converter - Table Dimensions should not break words in head row when autowidth option is set
rspec ./spec/video_spec.rb:34 # Asciidoctor::PDF::Converter - Video Vimeo should replace video with poster image if allow-uri-read attribute is set
```
Many of these test failures look minor (float vs integer comparisons). I'm not sure why the Vimeo test fails.

By the way, which dependency are supposed to propagate text-hyphen and open-uri-cached? I don't see these list as asciidoctor-pdf's dependencies, yet they appear to be needed for the test suite to succeed.

**Comment by mojavelinux** [comment] 2020-07-15 08:48
Are you by chance using an outdated branch? I ask that because these issues have already been discussed and addressed in issue #1542. There was a problem with Asciidoctor PDF when using the latest version of pdf-core, but that has been fixed and now we test against it continuously on each commit: https://travis-ci.org/github/asciidoctor/asciidoctor-pdf/jobs/708248755.

>  I'm not sure why the Vimeo test fails.

It looks like your environment is not allowing a connection to Vimeo. If your environment is not allowed to make external connections, pass the `-t ~network` option to the `rspec` command.

> which dependency are supposed to propagate text-hyphen and open-uri-cached

Optional dependencies are only defined in the test environment by the Gemfile. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/Gemfile

**Comment by Apteryks** [comment] 2020-07-15 13:47
Hello @mojavelinux! 

Thank you for the prompt replies. I thought I was already using master, but it seems not! With the latest master (commit f25ea78103bdead6e9ab7f344ebca4d2aa127a84) I now get:

```
starting phase `check'
Run options: exclude {:network=>true}
......................................asciidoctor: WARNING: problem encountered in image: /tmp/guix-build-ruby-asciidoctor-pdf-1.5.3-1.f25ea78.drv-0/source/spec/fixtures/svg-with-remote-image.svg; Error retrieving URL https://cdn.jsdelivr.net/gh/asciidoctor/asciidoctor-pdf@v1.5.0.rc.2/spec/fixtures/logo.png: Failed to open TCP connection to cdn.jsdelivr.net:443 (getaddrinfo: Name or service not known)


.................F.F...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................FF............................

Failures:

  1) Asciidoctor::PDF::Converter - Audio should replace audio block with right pointer, absolute path to audio file, and audio label
     Failure/Error: (expect pdf.lines).to eql expected_lines

       expected: ["before", "► /tmp/guix-build-ruby-asciidoctor-pdf-1.5.3-1.f25ea78.drv-0/source/spec/fixtures/podcast.mp3 (audio)", "after"]
            got: ["before", "► /tmp/guix-build-ruby-asciidoctor-pdf-1.5.3-1.f25ea78.drv-0/source/spec/fixtures/podcast.mp3", "(audio)", "after"]

       (compared using eql?)
     # ./spec/audio_spec.rb:21:in `block (2 levels) in <top (required)>'

  2) Asciidoctor::PDF::Converter - Audio should show caption for audio if title is specified
     Failure/Error: (expect pdf.lines).to eql [%(\uf04b\u00a0#{fixture_file 'podcast-e1.mp3'} (audio)), 'Episode 1 of my podcast']

       expected: [" /tmp/guix-build-ruby-asciidoctor-pdf-1.5.3-1.f25ea78.drv-0/source/spec/fixtures/podcast-e1.mp3 (audio)", "Episode 1 of my podcast"]
            got: [" /tmp/guix-build-ruby-asciidoctor-pdf-1.5.3-1.f25ea78.drv-0/source/spec/fixtures/podcast-e1.mp3(audio)", "Episode 1 of my podcast"]

       (compared using eql?)
     # ./spec/audio_spec.rb:46:in `block (2 levels) in <top (required)>'

  3) Asciidoctor::PDF::Converter - Video Local should replace video with video path and play icon if poster not specified
     Failure/Error: (expect pdf.lines).to eql [%(\uf04b\u00a0#{fixture_file 'asciidoctor.mp4'} (video))]

       expected: [" /tmp/guix-build-ruby-asciidoctor-pdf-1.5.3-1.f25ea78.drv-0/source/spec/fixtures/asciidoctor.mp4 (video)"]
            got: [" /tmp/guix-build-ruby-asciidoctor-pdf-1.5.3-1.f25ea78.drv-0/source/spec/fixtures/asciidoctor.mp4(video)"]

       (compared using eql?)
     # ./spec/video_spec.rb:22:in `block (3 levels) in <top (required)>'

  4) Asciidoctor::PDF::Converter - Video Local should show caption for video with no poster if title is specified
     Failure/Error: (expect pdf.lines).to eql [%(\uf04b\u00a0#{fixture_file 'asciidoctor.mp4'} (video)), 'Asciidoctor training']

       expected: [" /tmp/guix-build-ruby-asciidoctor-pdf-1.5.3-1.f25ea78.drv-0/source/spec/fixtures/asciidoctor.mp4 (video)", "Asciidoctor training"]
            got: [" /tmp/guix-build-ruby-asciidoctor-pdf-1.5.3-1.f25ea78.drv-0/source/spec/fixtures/asciidoctor.mp4(video)", "Asciidoctor training"]

       (compared using eql?)
     # ./spec/video_spec.rb:33:in `block (3 levels) in <top (required)>'

Finished in 3 minutes 24.2 seconds (files took 1.18 seconds to load)
1335 examples, 4 failures

Failed examples:

rspec ./spec/audio_spec.rb:6 # Asciidoctor::PDF::Converter - Audio should replace audio block with right pointer, absolute path to audio file, and audio label
rspec ./spec/audio_spec.rb:38 # Asciidoctor::PDF::Converter - Audio should show caption for audio if title is specified
rspec ./spec/video_spec.rb:15 # Asciidoctor::PDF::Converter - Video Local should replace video with video path and play icon if poster not specified
rspec ./spec/video_spec.rb:25 # Asciidoctor::PDF::Converter - Video Local should show caption for video with no poster if title is specified

command "rspec" "-t" "~network" failed with status 1
```

Which is much better! Any hindsights on the remaining failures? Thank you!

**Comment by mojavelinux** [comment] 2020-07-15 19:15
It appears certain spaces are being dropped. I'm not sure what the cause is. My hunch is that it has to do with the version of ttfunk (1.6.2.1 vs 1.5.1), but I'm not sure.

**Comment by mojavelinux** [comment] 2020-07-15 19:19
Nope, I just tested with ttfunk 1.6.2.1 and those tests pass. So it's not that.

**Comment by Apteryks** [comment] 2020-07-17 16:01
Hi @mojavelinux, thanks for your help! I've continued investigating using the latest master branch, and found that the problems appear only when the build is run inside the minimal container set by Guix. 

I'll investigate some more, but if I can't fail the source of the discrepancy, I'll just disable those four tests and move on. Thanks for the support!

**Closed** 2020-07-17 18:35 UTC

**Comment by mojavelinux** [comment] 2020-07-17 20:39
Sounds good. If there's anything else I can do to help, please let me know.

**Comment by Apteryks** [comment] 2020-07-20 01:53
Thanks again. FYI, there's now been a `ruby-asciidoctor-pdf` package in GNU Guix for the last 2 days :-) https://git.savannah.gnu.org/cgit/guix.git/commit/?id=9c5a7d0012944809128eca76938e8eb573abc979.

**Comment by mojavelinux** [comment] 2020-07-20 05:44
Thanks! Nice work!

**Comment by Apteryks** [comment] 2023-01-06 18:10
For the record, I'm happy to report this no longer affects `ruby-asciidoctor-pdf` as packaged in Guix.
