### ISSUE TITLE
Transparency in Watermark Image

### ISSUE THREAD

**Issue by nvdl** [asciidoctor/asciidoctor-pdf#716] opened 2016-12-22 10:49 UTC
Good to support transparency in watermark image by specifying it.
Besides, it will be nice if the watermark image order in the stack is also configurable.

Something like:

50% transparent image on top of document contents.
`:page-background-image: image:watermark.png[], alpha:50, placement:top`

50% transparent image at the bottom of document (alpha blending with background color of the document).
`:page-background-image: image:watermark.png[], alpha:50, placement:bottom`

No alpha, bottom placement.
`:page-background-image: image:watermark.png[]`

Good to have offset as well so that a smaller image can be positioned.

`:page-background-image: image:watermark.png[], xoffset:100, yoffset:500`

**Comment by mojavelinux** [comment] 2016-12-22 11:08
Good news. Transparency does work in PDF using Prawn. So we can support that.

I agree we need a way to specify a true watermark, which is placed above the content. However, we shouldn't block the ability to use a background image too, so we need a dedicated key.

```
:page-watermark-image: image:watermark[opacity=50%]
```

Like a page background, the watermark is assumed to be centered on the page. If you want a specific placement, you need to make an image the size of the page and layout the text where you want it to appear.

While we could support opacity as a property on the image, an even simpler way is to just add transparency to the image itself (which, of course, needs to be a PNG).

**Comment by mojavelinux** [comment] 2016-12-22 11:10
Background images don't yet honor the pdfwidth and align attributes. They probably should. We don't currently have anyway of specifying vertical alignment, though we could add a vertical-align attribute.

**Comment by mojavelinux** [comment] 2019-08-16 07:52
> Background  images don't yet honor the pdfwidth and align attributes. They probably  should. We don't currently have any way of specifying vertical  alignment, though we could add a vertical-align attribute.

This is now implemented.

**Comment by mojavelinux** [comment] 2019-10-11 07:56
This is a duplicate of #727 and has been fully implemented in the latest release.

**Closed by mojavelinux** 2019-10-11 07:56 UTC
Labels: duplicate
